import fs from 'node:fs/promises';
import {readFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawn, spawnSync} from 'node:child_process';
import assert from 'node:assert/strict';
import solc from 'solc';
import {createPublicClient, createWalletClient, http, parseEther, keccak256, encodeFunctionData, parseAbi} from 'viem';
import {privateKeyToAccount} from 'viem/accounts';
import {foundry} from 'viem/chains';

const here=path.dirname(fileURLToPath(import.meta.url)), root=path.resolve(here,'../..');
const contractRoot=path.resolve(root,'../ZNS-contract');
const sources={};
for(const file of ['contracts/ZnsBatchAccount.sol','contracts/ZcashNameService.sol'])
  sources[file]={content:await fs.readFile(path.join(contractRoot,file),'utf8')};
sources['TestToken.sol']={content:`pragma solidity 0.8.34;
contract TestToken { uint8 public constant decimals=8; string public constant symbol="cbZEC";
mapping(address=>uint256)public balanceOf;mapping(address=>mapping(address=>uint256))public allowance;
function mint(address a,uint256 v)external{balanceOf[a]+=v;}
function approve(address a,uint256 v)external returns(bool){allowance[msg.sender][a]=v;return true;}
function transfer(address a,uint256 v)external returns(bool){balanceOf[msg.sender]-=v;balanceOf[a]+=v;return true;}
function transferFrom(address f,address t,uint256 v)external returns(bool){allowance[f][msg.sender]-=v;balanceOf[f]-=v;balanceOf[t]+=v;return true;}}
contract TestSwap { TestToken immutable token; constructor(TestToken t){token=t;} function buy(uint256 amount)external payable{token.mint(msg.sender,amount);} }
`};
const settings={optimizer:{enabled:true,runs:200},viaIR:true,evmVersion:'prague',outputSelection:{'*':{'*':['abi','evm.bytecode.object','evm.deployedBytecode.object']}}};
const output=JSON.parse(solc.compile(JSON.stringify({language:'Solidity',sources,settings}), {import: file => ({contents: readFileSync(path.join(contractRoot,'node_modules',file),'utf8')})}));
const errors=(output.errors??[]).filter(x=>x.severity==='error');
assert.equal(errors.length,0,errors.map(x=>x.formattedMessage).join('\n'));
const artifact=(file,name)=>output.contracts[file][name];
const batch=artifact('contracts/ZnsBatchAccount.sol','ZnsBatchAccount');
const runtime='0x'+batch.evm.deployedBytecode.object;
await fs.mkdir(path.join(here,'output'),{recursive:true});
await fs.writeFile(path.join(here,'output/artifacts.json'),JSON.stringify(output.contracts,null,2));
await fs.writeFile(path.join(root,'lib/src/features/zns/application/zns_batch_bytecode.dart'),
  `// Generated by scripts/zns/qualify.mjs, solc 0.8.34, optimizer 200, Prague.\n// Matching this runtime is required before an EIP-7702 authorization.\nconst znsBatchRuntime = '${runtime}';\nconst znsBatchCodeHash = '${keccak256(runtime)}';\n`);
if(process.argv.includes('--compile-only')){console.log('Compiled registry and batch runtime.');process.exit(0);}
const signer=path.join(root,'rust/zns-core/target/debug/examples/local_sign');
function core(request){const p=spawnSync(signer,[],{input:JSON.stringify(request),encoding:'utf8',timeout:30000});assert.equal(p.status,0,p.error?.message??p.stderr);return JSON.parse(p.stdout);}
const owner=core({}).address;
const fork=process.argv.includes('--base-fork');
const port=fork?18550:18549;
const node=spawn(path.join(here,'node_modules/.bin/anvil'),['--host','127.0.0.1','--port',String(port),'--chain-id','31337','--hardfork','prague','--silent',...(fork?['--fork-url','https://mainnet.base.org']:[])],{stdio:['ignore','ignore','pipe']});
let nodeError='';node.stderr.on('data',d=>nodeError+=d.toString());node.on('error',e=>nodeError+=e.message);
const transport=http(`http://127.0.0.1:${port}`,{timeout:2000,retryCount:0});
const pub=createPublicClient({chain:foundry,transport});
// Standard public Anvil development account. Never used on a real network.
const account=privateKeyToAccount('0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80');
const wallet=createWalletClient({account,chain:foundry,transport});
const checks=[];
try {
  let ready=false;for(let i=0;i<30;i++){if(node.exitCode!==null||node.signalCode!==null||nodeError)break;try{await pub.getChainId();ready=true;break;}catch{await new Promise(r=>setTimeout(r,100));}}
  assert(ready,`Local Anvil failed: ${nodeError}`);
  assert.equal(await pub.getChainId(),31337);
  await pub.request({method:'anvil_setBalance',params:[owner,'0x8ac7230489e80000']});
  async function deploy(a,args=[]){const hash=await wallet.deployContract({abi:a.abi,bytecode:'0x'+a.evm.bytecode.object,args});const receipt=await pub.waitForTransactionReceipt({hash});assert.equal(receipt.status,'success');return receipt.contractAddress;}
  const tokenArtifact=artifact('TestToken.sol','TestToken');
  const token=fork?'0xB2000000000000000000008501b13360000cb2EC':await deploy(tokenArtifact);
  const holder='0x0fc47c17af86078d809358db1b4db2debc988566';
  async function fundToken(amount){
    if(!fork){await wallet.writeContract({address:token,abi:tokenArtifact.abi,functionName:'mint',args:[owner,amount]});return;}
    assert((await pub.readContract({address:token,abi:tokenArtifact.abi,functionName:'balanceOf',args:[holder]}))>=amount);
    await pub.request({method:'anvil_setBalance',params:[holder,'0xde0b6b3a7640000']});
    await pub.request({method:'anvil_impersonateAccount',params:[holder]});
    const h=await pub.request({method:'eth_sendTransaction',params:[{from:holder,to:token,data:encodeFunctionData({abi:tokenArtifact.abi,functionName:'transfer',args:[owner,amount]}),gas:'0x30d40'}]});
    assert.equal((await pub.waitForTransactionReceipt({hash:h})).status,'success');
    await pub.request({method:'anvil_stopImpersonatingAccount',params:[holder]});
  }
  assert.equal(await pub.readContract({address:token,abi:tokenArtifact.abi,functionName:'decimals'}),8);
  const registryArtifact=artifact('contracts/ZcashNameService.sol','ZcashNameService');
  const registry=await deploy(registryArtifact,[token,6000n]);
  const delegate=await deploy(batch);
  const rollbackToken=fork?await deploy(tokenArtifact):token;
  const swap=await deploy(artifact('TestToken.sol','TestSwap'),[rollbackToken]);
  const config={chainId:31337,allowTestChain:true,registry,token,delegate,
    protocolId:'0x32820c0b6a02f887a3de9a376a6e3c69a6b64b309f1bb809161039668d593760',
    maxValueWei:parseEther('1').toString(),maxGasLimit:'3000000',maxFeePerGasWei:'100000000000',maxTotalFeeWei:'100000000000000000',maxTokenAmount:'100000000'};
  const secret='0x'+'11'.repeat(32),ua='local-contract-fixture-address';
  const op={kind:'commit',name:'alice',unifiedAddress:ua,secret};
  const prepared=core({config,operation:op}).prepared;
  const chainCommit=await pub.readContract({address:registry,abi:registryArtifact.abi,functionName:'makeCommitment',args:['alice',ua,owner,secret]});
  assert.equal(prepared.commitment,chainCommit);checks.push('Rust commitment equals deployed Solidity');
  async function send(operation){const nonce=await pub.getTransactionCount({address:owner,blockTag:'pending'});
    const signed=core({config,operation,transaction:{nonce:String(nonce),gasLimit:'3000000',maxFeePerGas:'10000000000',maxPriorityFeePerGas:'1000000000',l1FeeWei:'0'}}).signed;
    const hash=await pub.sendRawTransaction({serializedTransaction:signed.rawTransaction});assert.equal(hash,signed.transactionHash);
    return pub.waitForTransactionReceipt({hash});}
  assert.equal((await send(op)).status,'success');
  const reveal={kind:'atomicRegister',name:'alice',unifiedAddress:ua,secret,amount:'6000',existingTokenUnits:'6000',swap:null,deadline:String((await pub.getBlock()).timestamp+600n)};
  // First reveal fails before maturity. EIP-7702 delegation persists, but token
  // allowance/state changes are rolled back with the failed execution.
  assert.equal((await send(reveal)).status,'reverted');
  assert.equal(await pub.readContract({address:token,abi:tokenArtifact.abi,functionName:'allowance',args:[owner,registry]}),0n);
  assert.equal(await pub.getCode({address:owner}),'0xef0100'+delegate.slice(2).toLowerCase());
  checks.push('Immature reveal reverts atomically; delegation persistence explicit');
  await fundToken(6000n);
  await pub.request({method:'evm_increaseTime',params:[61]});await pub.request({method:'evm_mine',params:[]});
  const snap=await pub.request({method:'evm_snapshot',params:[]});
  assert.equal((await send(reveal)).status,'success');
  const record=await pub.readContract({address:registry,abi:registryArtifact.abi,functionName:'recordOf',args:['alice']});
  assert.equal(record[0].toLowerCase(),owner.toLowerCase());assert.equal(record[1],ua);assert.equal(record[3],true);
  assert.equal(await pub.readContract({address:token,abi:tokenArtifact.abi,functionName:'balanceOf',args:[registry]}),6000n);
  checks.push('Rust-signed self-funded EIP-7702 registration preserves owner and full deposit');
  assert(await pub.request({method:'evm_revert',params:[snap]}));
  assert.equal((await pub.readContract({address:registry,abi:registryArtifact.abi,functionName:'recordOf',args:['alice']}))[3],false);
  checks.push('Local reorg removes registration while preserving recoverable commitment');
  assert.equal((await send(reveal)).status,'success');
  const positionId=await pub.readContract({address:registry,abi:registryArtifact.abi,functionName:'positionIdOf',args:['alice']});
  const info=await pub.readContract({address:registry,abi:registryArtifact.abi,functionName:'positionInfo',args:[positionId]});
  await pub.request({method:'evm_increaseTime',params:[365*24*60*60]});await pub.request({method:'evm_mine',params:[]});
  assert.equal((await send({kind:'refresh',positionId:String(positionId)})).status,'success');
  assert.equal((await send({kind:'update',positionId:String(positionId),unifiedAddress:'updated-fixture-address'})).status,'success');
  assert.equal((await send({kind:'claimRewards',positionId:String(positionId)})).status,'success');
  const refreshed=await pub.readContract({address:registry,abi:registryArtifact.abi,functionName:'positionInfo',args:[positionId]});
  assert.equal(refreshed[4],info[4]);
  assert.equal((await send({kind:'release',positionId:String(positionId)})).status,'success');
  assert.equal((await pub.readContract({address:registry,abi:registryArtifact.abi,functionName:'recordOf',args:['alice']}))[3],false);
  assert.equal(await pub.readContract({address:token,abi:tokenArtifact.abi,functionName:'balanceOf',args:[owner]}),6000n);
  checks.push('Rust-signed refresh/update/claim preserve maturity; mature release returns full deposit');
  const longName='a'.repeat(63),longUA='u'.repeat(512),longSecret='0x'+'33'.repeat(32);
  assert.equal((await send({kind:'commit',name:longName,unifiedAddress:longUA,secret:longSecret})).status,'success');
  await pub.request({method:'evm_increaseTime',params:[61]});await pub.request({method:'evm_mine',params:[]});
  const longReceipt=await send({...reveal,name:longName,unifiedAddress:longUA,secret:longSecret,deadline:String((await pub.getBlock()).timestamp+600n)});
  assert.equal(longReceipt.status,'success');assert(longReceipt.gasUsed<3000000n);
  checks.push(`Maximum-length Rust-signed atomic registration succeeds (${longReceipt.gasUsed} gas)`);
  const extraSecret='0x'+'44'.repeat(32);
  await fundToken(6000n);
  assert.equal((await send({kind:'commit',name:'second',unifiedAddress:ua,secret:extraSecret})).status,'success');
  await pub.request({method:'evm_increaseTime',params:[61]});await pub.request({method:'evm_mine',params:[]});
  assert.equal((await send({...reveal,name:'second',secret:extraSecret,deadline:String((await pub.getBlock()).timestamp+600n)})).status,'success');
  assert.equal(await pub.readContract({address:registry,abi:registryArtifact.abi,functionName:'balanceOf',args:[owner]}),2n);
  checks.push('One software account registers multiple independent NFTs');
  const giftId=await pub.readContract({address:registry,abi:registryArtifact.abi,functionName:'positionIdOf',args:['second']});
  const giftBefore=await pub.readContract({address:registry,abi:registryArtifact.abi,functionName:'positionInfo',args:[giftId]});
  assert.equal((await send({kind:'transfer',positionId:String(giftId),recipient:account.address})).status,'success');
  let gift=await pub.readContract({address:registry,abi:registryArtifact.abi,functionName:'positionInfo',args:[giftId]});
  assert.equal(gift[0].toLowerCase(),account.address.toLowerCase());assert.equal(gift[2],'');assert.deepEqual(gift.slice(3),giftBefore.slice(3));
  const returnGift=await wallet.writeContract({address:registry,abi:registryArtifact.abi,functionName:'safeTransferFrom',args:[account.address,owner,giftId]});
  assert.equal((await pub.waitForTransactionReceipt({hash:returnGift})).status,'success');
  gift=await pub.readContract({address:registry,abi:registryArtifact.abi,functionName:'positionInfo',args:[giftId]});
  assert.equal(gift[0].toLowerCase(),owner.toLowerCase());assert.equal(gift[2],'');assert.deepEqual(gift.slice(3),giftBefore.slice(3));
  checks.push('Rust-signed NFT gift and safe return to a delegated account preserve financial rights and dates');
  const buy=encodeFunctionData({abi:parseAbi(['function buy(uint256 amount) payable']),functionName:'buy',args:[7000n]});
  const failing=encodeFunctionData({abi:registryArtifact.abi,functionName:'register',args:['alice',ua,'0x'+'22'.repeat(32)]});
  const before=await pub.readContract({address:rollbackToken,abi:tokenArtifact.abi,functionName:'balanceOf',args:[owner]});
  await pub.request({method:'anvil_impersonateAccount',params:[owner]});
  const external=encodeFunctionData({abi:batch.abi,functionName:'execute',args:[[{target:swap,value:1n,data:buy},{target:registry,value:0n,data:failing}],(await pub.getBlock()).timestamp+60n]});
  const h=await pub.request({method:'eth_sendTransaction',params:[{from:owner,to:owner,data:external,gas:'0xf4240'}]});
  assert.equal((await pub.waitForTransactionReceipt({hash:h})).status,'reverted');
  assert.equal(await pub.readContract({address:rollbackToken,abi:tokenArtifact.abi,functionName:'balanceOf',args:[owner]}),before);
  await pub.request({method:'anvil_stopImpersonatingAccount',params:[owner]});
  checks.push('Destination failure rolls back an earlier swap-like asset purchase');
  await assert.rejects(pub.call({account:account.address,to:owner,data:external}));
  checks.push('External caller cannot execute the delegated account');
  const result={testedAt:new Date().toISOString(),baseMainnetFork:fork,chainId:31337,delegateCodeHash:keccak256(runtime),owner,registry,token,delegate,checks,
    limits:(fork?'Local Base mainnet fork with real cbZEC contract state; token funding uses local impersonation. ':'Local synthetic chain/token only. ')+ ' Zcash funding, live liquidity, Base fees and full Flutter signing not exercised. Test UA strings exercise contract behavior; wallet separately validates ZIP316.'};
  await fs.writeFile(path.join(here,fork?'output/base-fork-qualification.json':'output/qualification.json'),JSON.stringify(result,null,2));
  console.log(JSON.stringify(result,null,2));
} finally {node.kill('SIGTERM');}
