// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class GiftCardUsageEvidence {
  final String status;
  final String? reason;
  final BigInt verifiedHeight;
  final List<String> spendingTxids;
  final BigInt spentHeight;
  final bool canDelete;

  const GiftCardUsageEvidence({
    required this.status,
    this.reason,
    required this.verifiedHeight,
    required this.spendingTxids,
    required this.spentHeight,
    required this.canDelete,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      reason.hashCode ^
      verifiedHeight.hashCode ^
      spendingTxids.hashCode ^
      spentHeight.hashCode ^
      canDelete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GiftCardUsageEvidence &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          reason == other.reason &&
          verifiedHeight == other.verifiedHeight &&
          spendingTxids == other.spendingTxids &&
          spentHeight == other.spentHeight &&
          canDelete == other.canDelete;
}
