// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

Future<ContactIdentityResult> contactsCreateIdentity() =>
    RustLib.instance.api.crateApiContactsContactsCreateIdentity();

Future<bool> contactsValidateUnifiedAddress({
  required String network,
  required String address,
}) => RustLib.instance.api.crateApiContactsContactsValidateUnifiedAddress(
  network: network,
  address: address,
);

Future<ContactRequestResult> contactsCreateRequest({
  required String network,
  String? subjectIdentity,
  required BigInt now,
}) => RustLib.instance.api.crateApiContactsContactsCreateRequest(
  network: network,
  subjectIdentity: subjectIdentity,
  now: now,
);

Future<ContactRequestResult> contactsInspectRequest({
  required String network,
  required String requestJson,
  required BigInt now,
}) => RustLib.instance.api.crateApiContactsContactsInspectRequest(
  network: network,
  requestJson: requestJson,
  now: now,
);

Future<String> contactsSignResponse({
  required String network,
  required String requestJson,
  required List<int> secretKey,
  required String address,
  required BigInt sequence,
  required BigInt now,
}) => RustLib.instance.api.crateApiContactsContactsSignResponse(
  network: network,
  requestJson: requestJson,
  secretKey: secretKey,
  address: address,
  sequence: sequence,
  now: now,
);

Future<ContactEndpointResult> contactsVerifyResponse({
  required String network,
  required String requestJson,
  required String exchangeJson,
  required BigInt now,
}) => RustLib.instance.api.crateApiContactsContactsVerifyResponse(
  network: network,
  requestJson: requestJson,
  exchangeJson: exchangeJson,
  now: now,
);

Future<bool> contactsValidateIntroductionAssociation({
  required String network,
  required String incomingIdentity,
  required String ownIdentity,
  required List<int> ownSecretKey,
}) => RustLib.instance.api
    .crateApiContactsContactsValidateIntroductionAssociation(
      network: network,
      incomingIdentity: incomingIdentity,
      ownIdentity: ownIdentity,
      ownSecretKey: ownSecretKey,
    );

Future<ContactIntroductionResult> contactsCreateIntroductionAsk({
  required String network,
  required String peerAcIdentity,
  required List<int> secretCaKey,
  required BigInt now,
}) => RustLib.instance.api.crateApiContactsContactsCreateIntroductionAsk(
  network: network,
  peerAcIdentity: peerAcIdentity,
  secretCaKey: secretCaKey,
  now: now,
);

Future<ContactIntroductionResult> contactsVerifyIntroductionAsk({
  required String network,
  required String peerCaIdentity,
  required String ownAcIdentity,
  required String packetJson,
  required BigInt now,
}) => RustLib.instance.api.crateApiContactsContactsVerifyIntroductionAsk(
  network: network,
  peerCaIdentity: peerCaIdentity,
  ownAcIdentity: ownAcIdentity,
  packetJson: packetJson,
  now: now,
);

Future<ContactIntroductionResult> contactsCreateIntroductionOffer({
  required String network,
  required String requestJson,
  required String peerBaIdentity,
  required List<int> secretAbKey,
  required String suggestedRecipient,
  required BigInt now,
}) => RustLib.instance.api.crateApiContactsContactsCreateIntroductionOffer(
  network: network,
  requestJson: requestJson,
  peerBaIdentity: peerBaIdentity,
  secretAbKey: secretAbKey,
  suggestedRecipient: suggestedRecipient,
  now: now,
);

Future<ContactIntroductionResult> contactsVerifyIntroductionOffer({
  required String network,
  required String peerAbIdentity,
  required String ownBaIdentity,
  required String packetJson,
  required BigInt now,
}) => RustLib.instance.api.crateApiContactsContactsVerifyIntroductionOffer(
  network: network,
  peerAbIdentity: peerAbIdentity,
  ownBaIdentity: ownBaIdentity,
  packetJson: packetJson,
  now: now,
);

Future<ContactIntroductionResult> contactsCreateIntroductionConsent({
  required String network,
  required String peerAbIdentity,
  required List<int> secretBaKey,
  required List<int> freshSecretBcKey,
  required String freshAddress,
  required String offerPacketJson,
  required BigInt now,
}) => RustLib.instance.api.crateApiContactsContactsCreateIntroductionConsent(
  network: network,
  peerAbIdentity: peerAbIdentity,
  secretBaKey: secretBaKey,
  freshSecretBcKey: freshSecretBcKey,
  freshAddress: freshAddress,
  offerPacketJson: offerPacketJson,
  now: now,
);

Future<ContactIntroductionResult> contactsVerifyIntroductionConsent({
  required String network,
  required String peerBaIdentity,
  required String ownAbIdentity,
  required String savedRequestJson,
  required String savedOfferJson,
  required String packetJson,
  required BigInt now,
}) => RustLib.instance.api.crateApiContactsContactsVerifyIntroductionConsent(
  network: network,
  peerBaIdentity: peerBaIdentity,
  ownAbIdentity: ownAbIdentity,
  savedRequestJson: savedRequestJson,
  savedOfferJson: savedOfferJson,
  packetJson: packetJson,
  now: now,
);

Future<ContactIntroductionResult> contactsCreateIntroductionDelivery({
  required String network,
  required String peerBaIdentity,
  required String ownAbIdentity,
  required String peerCaIdentity,
  required List<int> secretAcKey,
  required String savedRequestJson,
  required String savedOfferJson,
  required String consentPacketJson,
  required String suggestedContact,
  required BigInt now,
}) => RustLib.instance.api.crateApiContactsContactsCreateIntroductionDelivery(
  network: network,
  peerBaIdentity: peerBaIdentity,
  ownAbIdentity: ownAbIdentity,
  peerCaIdentity: peerCaIdentity,
  secretAcKey: secretAcKey,
  savedRequestJson: savedRequestJson,
  savedOfferJson: savedOfferJson,
  consentPacketJson: consentPacketJson,
  suggestedContact: suggestedContact,
  now: now,
);

Future<ContactIntroductionResult> contactsVerifyIntroductionDelivery({
  required String network,
  required String peerAcIdentity,
  required String ownCaIdentity,
  required String savedRequestJson,
  required String packetJson,
  required BigInt now,
}) => RustLib.instance.api.crateApiContactsContactsVerifyIntroductionDelivery(
  network: network,
  peerAcIdentity: peerAcIdentity,
  ownCaIdentity: ownCaIdentity,
  savedRequestJson: savedRequestJson,
  packetJson: packetJson,
  now: now,
);

class ContactEndpointResult {
  final String identity;
  final String address;
  final BigInt sequence;
  final BigInt expiresAt;
  final String network;

  const ContactEndpointResult({
    required this.identity,
    required this.address,
    required this.sequence,
    required this.expiresAt,
    required this.network,
  });

  @override
  int get hashCode =>
      identity.hashCode ^
      address.hashCode ^
      sequence.hashCode ^
      expiresAt.hashCode ^
      network.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactEndpointResult &&
          runtimeType == other.runtimeType &&
          identity == other.identity &&
          address == other.address &&
          sequence == other.sequence &&
          expiresAt == other.expiresAt &&
          network == other.network;
}

class ContactIdentityResult {
  final String identity;
  final Uint8List secretKey;

  const ContactIdentityResult({
    required this.identity,
    required this.secretKey,
  });

  @override
  int get hashCode => identity.hashCode ^ secretKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactIdentityResult &&
          runtimeType == other.runtimeType &&
          identity == other.identity &&
          secretKey == other.secretKey;
}

/// Cryptographically verified introduction candidate. These fields do not
/// authorize consent, contact acceptance, transport or payment. The coordinator
/// must recheck current accepted associations and atomically consume sessions.
class ContactIntroductionResult {
  final String packetJson;
  final String requestJson;
  final String requestHash;
  final String? endpointHash;
  final String? endorsementHash;
  final BigInt expiresAt;
  final String? offerJson;
  final String? endpointJson;
  final String? identity;
  final String? address;
  final BigInt? sequence;
  final String? suggestion;

  const ContactIntroductionResult({
    required this.packetJson,
    required this.requestJson,
    required this.requestHash,
    this.endpointHash,
    this.endorsementHash,
    required this.expiresAt,
    this.offerJson,
    this.endpointJson,
    this.identity,
    this.address,
    this.sequence,
    this.suggestion,
  });

  @override
  int get hashCode =>
      packetJson.hashCode ^
      requestJson.hashCode ^
      requestHash.hashCode ^
      endpointHash.hashCode ^
      endorsementHash.hashCode ^
      expiresAt.hashCode ^
      offerJson.hashCode ^
      endpointJson.hashCode ^
      identity.hashCode ^
      address.hashCode ^
      sequence.hashCode ^
      suggestion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactIntroductionResult &&
          runtimeType == other.runtimeType &&
          packetJson == other.packetJson &&
          requestJson == other.requestJson &&
          requestHash == other.requestHash &&
          endpointHash == other.endpointHash &&
          endorsementHash == other.endorsementHash &&
          expiresAt == other.expiresAt &&
          offerJson == other.offerJson &&
          endpointJson == other.endpointJson &&
          identity == other.identity &&
          address == other.address &&
          sequence == other.sequence &&
          suggestion == other.suggestion;
}

class ContactRequestResult {
  final String requestJson;
  final String audience;
  final String challenge;
  final BigInt expiresAt;
  final String? subjectIdentity;

  const ContactRequestResult({
    required this.requestJson,
    required this.audience,
    required this.challenge,
    required this.expiresAt,
    this.subjectIdentity,
  });

  @override
  int get hashCode =>
      requestJson.hashCode ^
      audience.hashCode ^
      challenge.hashCode ^
      expiresAt.hashCode ^
      subjectIdentity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactRequestResult &&
          runtimeType == other.runtimeType &&
          requestJson == other.requestJson &&
          audience == other.audience &&
          challenge == other.challenge &&
          expiresAt == other.expiresAt &&
          subjectIdentity == other.subjectIdentity;
}
