// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> contactBackupEncrypt({
  required String dbPath,
  required String network,
  required String accountUuid,
  required List<int> secretBytes,
  required List<int> plainBytes,
}) => RustLib.instance.api.crateApiContactBackupContactBackupEncrypt(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  secretBytes: secretBytes,
  plainBytes: plainBytes,
);

Future<Uint8List> contactBackupDecrypt({
  required String dbPath,
  required String network,
  required String accountUuid,
  required List<int> secretBytes,
  required String archive,
}) => RustLib.instance.api.crateApiContactBackupContactBackupDecrypt(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  secretBytes: secretBytes,
  archive: archive,
);
