// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../wallet/gift_card_tracking.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> registerGiftCardObserver({
  required String dbPath,
  required String network,
  required List<int> mnemonicBytes,
  required String address,
  required BigInt birthdayHeight,
}) => RustLib.instance.api.crateApiGiftCardTrackingRegisterGiftCardObserver(
  dbPath: dbPath,
  network: network,
  mnemonicBytes: mnemonicBytes,
  address: address,
  birthdayHeight: birthdayHeight,
);

Future<void> syncGiftCardObservers({
  required String dbPath,
  required String network,
  required String lightwalletdUrl,
}) => RustLib.instance.api.crateApiGiftCardTrackingSyncGiftCardObservers(
  dbPath: dbPath,
  network: network,
  lightwalletdUrl: lightwalletdUrl,
);

void cancelGiftCardObserverSync({required String dbPath}) => RustLib
    .instance
    .api
    .crateApiGiftCardTrackingCancelGiftCardObserverSync(dbPath: dbPath);

Future<GiftCardUsageEvidence> inspectGiftCardUsage({
  required String dbPath,
  required String accountUuid,
  required String fundingTxids,
  required BigInt expectedFundingZatoshi,
  required String lightwalletdUrl,
}) => RustLib.instance.api.crateApiGiftCardTrackingInspectGiftCardUsage(
  dbPath: dbPath,
  accountUuid: accountUuid,
  fundingTxids: fundingTxids,
  expectedFundingZatoshi: expectedFundingZatoshi,
  lightwalletdUrl: lightwalletdUrl,
);

Future<void> removeGiftCardObserver({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiGiftCardTrackingRemoveGiftCardObserver(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

Future<List<String>> listGiftCardObservers({required String dbPath}) => RustLib
    .instance
    .api
    .crateApiGiftCardTrackingListGiftCardObservers(dbPath: dbPath);
