// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/zcash_voting/config.dart';
import '../third_party/zcash_voting/delegate.dart';
import '../third_party/zcash_voting/share_policy.dart';
import '../third_party/zcash_voting/wire.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'voting.dart';

// These functions are ignored because they are not marked as `pub`: `database_handle`, `delegation_inputs`, `drive`, `internal`, `invalid_input`, `pipeline`, `round_drive_policy`, `share_tracking_drive_policy`, `track`, `unix_now_seconds`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Opens a session bound to `ctx`'s account and round.
///
/// `stored_hotkey_secret` is required only for sessions that cast votes.
/// Chain, helper, PIR, and vote-tree traffic use the wallet's network route
/// through the shared voting client factory.
///
/// Synchronous on purpose for now: opening the sidecar can run schema
/// migrations, which would be better off the Dart isolate that draws the UI,
/// but the voting session fakes and their gate-based tests assume the handle
/// exists without an intervening event-loop turn. Moving it needs that
/// harness work, not just this signature.
VotingRoundSession openVotingRoundSession({
  required ApiVotingRoundContext ctx,
  required ApiRoundSessionBinding binding,
  Uint8List? storedHotkeySecret,
  required BigInt operationEpoch,
}) => RustLib.instance.api.crateApiVotingSessionOpenVotingRoundSession(
  ctx: ctx,
  binding: binding,
  storedHotkeySecret: storedHotkeySecret,
  operationEpoch: operationEpoch,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VotingRoundSession>>
abstract class VotingRoundSession implements RustOpaqueInterface {
  /// Cancels every step in flight or queued on this session.
  void cancel();

  /// Clears durable ballot intents for proposals outside the bound roster
  /// and re-plans.
  ///
  /// A decision recorded before a proposal left the authenticated
  /// configuration outlives that proposal. The planner reports those in
  /// `RoundPlanView::unrostered_intents` and withholds `CastVote` until
  /// they are cleared, because the round's immediate helper share is
  /// derived from the complete set of choices and a stale intent would
  /// make that set disagree with the roster.
  ///
  /// Pass the ids the plan reported. The SDK refuses to clear an intent
  /// whose vote the chain lifecycle already owns, but the planner omits
  /// exactly those from `unrostered_intents`, so a plan-sourced list is
  /// always clearable.
  Future<RoundPlanView> clearBallotIntents({required List<int> proposalIds});

  /// Re-reads whether this round's designated immediate share is confirmed.
  ///
  /// The one confirmation-only exception to the vote-end boundary: a helper
  /// may have confirmed the share before the deadline while the last
  /// tracking pass missed the transition. This never resubmits a share or
  /// selects a new helper, so it is safe after the round has ended, and it
  /// answers now rather than on the tracking cadence — the submission flow
  /// gates completion on it.
  Future<bool> confirmImmediateShare({
    required int bundleIndex,
    required int proposalId,
    required int shareIndex,
  });

  /// Whether this session has been cancelled.
  ///
  /// Background tracking and a foreground cast run on separate sessions for
  /// one round, so this is per-activity: cancelling the tracking session
  /// leaves the casting session running.
  bool isCancelled();

  /// Builds redacted Keystone signing requests for the given bundles.
  Future<List<KeystoneSigningRequest>> keystoneSigningRequests({
    required List<int> bundleIndices,
  });

  /// Plans the round from durable state.
  Future<RoundPlanView> plan();

  /// Drives the bound round to quiescence, streaming events then one report.
  ///
  /// Emits exactly one `Result` event for the reason [`Self::advance`]
  /// documents: a streaming function's `Err` return never reaches Dart.
  ///
  /// `host` is a template. The driver reads the host context once per
  /// dispatch and this bridge restamps `now_seconds` each time, because a
  /// run can take minutes and a long proof can cross the last-moment or
  /// vote-end boundary. Every other field is fixed for the run, so a helper
  /// fleet that changes mid-run needs a new call.
  Stream<ApiRoundRunEvent> runRound({
    ApiDelegationSignerInput? signer,
    ApiRoundDrivePolicy? policy,
  });

  /// Tracks this round's helper shares to confirmation, streaming events
  /// then exactly one report.
  ///
  /// Background tracking opens its own session, so `cancel` stops tracking
  /// without touching a foreground cast running on another session for the
  /// same round. That separation used to need a second cancellation handle
  /// and a second helper-health scope; one session per activity gives it for
  /// free, and each session's helper health now spans both the initial
  /// delivery it performed and the tracking that follows.
  Stream<ApiShareTrackingRunEvent> runShareTracking({
    ApiShareTrackingDrivePolicy? policy,
  });

  /// Records ballot decisions against the bound roster and re-plans.
  Future<RoundPlanView> setBallotIntents({
    required List<ApiBallotIntent> intents,
  });

  void setOperationEpoch({required BigInt operationEpoch});
}

/// One ballot decision to record before casting.
class ApiBallotIntent {
  final int proposalId;

  /// `true` records `Skipped`; otherwise `choice` is required.
  final bool skipped;
  final int? choice;

  const ApiBallotIntent({
    required this.proposalId,
    required this.skipped,
    this.choice,
  });

  @override
  int get hashCode => proposalId.hashCode ^ skipped.hashCode ^ choice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiBallotIntent &&
          runtimeType == other.runtimeType &&
          proposalId == other.proposalId &&
          skipped == other.skipped &&
          choice == other.choice;
}

class ApiDelegationSignerInput {
  final ApiDelegationSignerKind kind;
  final String? mnemonic;
  final Uint8List? keystoneSig;
  final Uint8List? keystoneSighash;

  const ApiDelegationSignerInput({
    required this.kind,
    this.mnemonic,
    this.keystoneSig,
    this.keystoneSighash,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      mnemonic.hashCode ^
      keystoneSig.hashCode ^
      keystoneSighash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDelegationSignerInput &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          mnemonic == other.mnemonic &&
          keystoneSig == other.keystoneSig &&
          keystoneSighash == other.keystoneSighash;
}

/// How a delegation step signs.
enum ApiDelegationSignerKind {
  /// Software account: `mnemonic` must be set.
  mnemonic,

  /// Keystone account: use the signature stored for the bundle.
  keystoneStored,

  /// Keystone account: use the provided signature bytes.
  keystoneProvided,
}

/// One proposal from the authenticated round configuration.
class ApiProposalRosterEntry {
  final int proposalId;
  final int numOptions;

  const ApiProposalRosterEntry({
    required this.proposalId,
    required this.numOptions,
  });

  @override
  int get hashCode => proposalId.hashCode ^ numOptions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiProposalRosterEntry &&
          runtimeType == other.runtimeType &&
          proposalId == other.proposalId &&
          numOptions == other.numOptions;
}

/// How a run paces itself. Omitted fields keep the SDK defaults, which are the
/// cadence the Dart driver used before the SDK owned the loop.
class ApiRoundDrivePolicy {
  final double? pendingRepollSeconds;
  final int? maxBundleConcurrency;
  final int? maxDispatches;

  /// `true` keeps every other bundle running after one fails.
  final bool? skipFailedBundle;

  /// `true` counts run progress against the round's selected choices
  /// instead of only the work this run picked up, so a resumed round keeps
  /// the total the voter already saw.
  ///
  /// Not the whole ballot: the SDK's `SelectedChoices` baseline excludes
  /// skips and clearable stale choices, because those owe no vote
  /// submission and would inflate a total the voter can never reach.
  /// Omitted keeps the SDK's run-relative default.
  final bool? selectedChoiceProgress;

  const ApiRoundDrivePolicy({
    this.pendingRepollSeconds,
    this.maxBundleConcurrency,
    this.maxDispatches,
    this.skipFailedBundle,
    this.selectedChoiceProgress,
  });

  @override
  int get hashCode =>
      pendingRepollSeconds.hashCode ^
      maxBundleConcurrency.hashCode ^
      maxDispatches.hashCode ^
      skipFailedBundle.hashCode ^
      selectedChoiceProgress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiRoundDrivePolicy &&
          runtimeType == other.runtimeType &&
          pendingRepollSeconds == other.pendingRepollSeconds &&
          maxBundleConcurrency == other.maxBundleConcurrency &&
          maxDispatches == other.maxDispatches &&
          skipFailedBundle == other.skipFailedBundle &&
          selectedChoiceProgress == other.selectedChoiceProgress;
}

/// One observation from a round run, or its single terminal report.
///
/// Exactly one `Result`-kind event is emitted however the run ends, carrying
/// either the report or a bridge error.
class ApiRoundRunEvent {
  final ApiRoundStepEventKind kind;
  final RoundDriveEventView? event;
  final RoundRunReportView? report;
  final ApiRoundStepError? error;

  const ApiRoundRunEvent({
    required this.kind,
    this.event,
    this.report,
    this.error,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ event.hashCode ^ report.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiRoundRunEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          event == other.event &&
          report == other.report &&
          error == other.error;
}

/// Everything one session binds for its whole life.
///
/// These used to be passed again on every call that ran work, which made
/// mapping a URL at one call site and not another a silent error. A session is
/// already bound to one account, round and roster; binding its endpoints and
/// timing beside them means a caller cannot supply a different fleet to two
/// steps of the same round.
///
/// The binding is fixed once taken. A configuration change replaces the
/// round's servers or timing, and Vizor answers that by rebuilding the
/// session rather than mutating a live one, so there is no update path here.
class ApiRoundSessionBinding {
  /// Vote-chain endpoints for submissions.
  final List<String> chainEndpoints;

  /// Complete configured helper fleet, already mapped to transport URLs.
  final List<String> configuredHelperUrls;

  /// Vote-tree node URLs tried in order by cast-vote steps.
  final List<String> voteTreeNodeUrls;

  /// PIR endpoints for delegation snapshot proofs, most preferred first.
  final List<String> pirServerUrls;

  /// The round's authenticated proposal roster.
  final List<ApiProposalRosterEntry> proposals;
  final BigInt? ceremonyStartSeconds;
  final BigInt? voteEndTimeSeconds;
  final int maxProofConcurrency;

  const ApiRoundSessionBinding({
    required this.chainEndpoints,
    required this.configuredHelperUrls,
    required this.voteTreeNodeUrls,
    required this.pirServerUrls,
    required this.proposals,
    this.ceremonyStartSeconds,
    this.voteEndTimeSeconds,
    required this.maxProofConcurrency,
  });

  @override
  int get hashCode =>
      chainEndpoints.hashCode ^
      configuredHelperUrls.hashCode ^
      voteTreeNodeUrls.hashCode ^
      pirServerUrls.hashCode ^
      proposals.hashCode ^
      ceremonyStartSeconds.hashCode ^
      voteEndTimeSeconds.hashCode ^
      maxProofConcurrency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiRoundSessionBinding &&
          runtimeType == other.runtimeType &&
          chainEndpoints == other.chainEndpoints &&
          configuredHelperUrls == other.configuredHelperUrls &&
          voteTreeNodeUrls == other.voteTreeNodeUrls &&
          pirServerUrls == other.pirServerUrls &&
          proposals == other.proposals &&
          ceremonyStartSeconds == other.ceremonyStartSeconds &&
          voteEndTimeSeconds == other.voteEndTimeSeconds &&
          maxProofConcurrency == other.maxProofConcurrency;
}

/// A typed bridge failure carried by a result event.
///
/// Mirrors [`VotingErrorView`] field for field instead of embedding it. The
/// bridge marks a type as a Dart exception only while it is used purely as an
/// error type; using the view as a struct field here would demote it to plain
/// data, and `#[frb(sync)]` entry points depend on that marker — the
/// generated `executeSync` rethrows only `FrbException`s and turns everything
/// else into a `PanicException`, which would cost
/// [`open_voting_round_session`] its typed failure.
///
/// [`From`] destructures the view exhaustively, so a field added upstream
/// fails the build here rather than silently disappearing on this path.
class ApiRoundStepError {
  final VotingErrorKindView kind;
  final bool retryable;
  final String message;
  final int? bundleIndex;
  final DelegationSetupFieldView? setupField;
  final BigInt? snapshotHeight;
  final BigInt? requiredWeightZatoshi;
  final BigInt? selectedWeightZatoshi;
  final int? bundleNoteSlots;
  final int? selectedNotes;
  final int? httpStatus;
  final String? endpoint;

  const ApiRoundStepError({
    required this.kind,
    required this.retryable,
    required this.message,
    this.bundleIndex,
    this.setupField,
    this.snapshotHeight,
    this.requiredWeightZatoshi,
    this.selectedWeightZatoshi,
    this.bundleNoteSlots,
    this.selectedNotes,
    this.httpStatus,
    this.endpoint,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      retryable.hashCode ^
      message.hashCode ^
      bundleIndex.hashCode ^
      setupField.hashCode ^
      snapshotHeight.hashCode ^
      requiredWeightZatoshi.hashCode ^
      selectedWeightZatoshi.hashCode ^
      bundleNoteSlots.hashCode ^
      selectedNotes.hashCode ^
      httpStatus.hashCode ^
      endpoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiRoundStepError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          retryable == other.retryable &&
          message == other.message &&
          bundleIndex == other.bundleIndex &&
          setupField == other.setupField &&
          snapshotHeight == other.snapshotHeight &&
          requiredWeightZatoshi == other.requiredWeightZatoshi &&
          selectedWeightZatoshi == other.selectedWeightZatoshi &&
          bundleNoteSlots == other.bundleNoteSlots &&
          selectedNotes == other.selectedNotes &&
          httpStatus == other.httpStatus &&
          endpoint == other.endpoint;
}

enum ApiRoundStepEventKind { progress, result }

/// How a tracking run paces itself. Omitted fields keep the SDK defaults.
class ApiShareTrackingDrivePolicy {
  final double? failureRetrySeconds;
  final int? maxConsecutiveFailures;

  /// Passes before the run stops with `PassBudgetExhausted`. Omitted keeps
  /// the SDK default of no bound at all: vote end, confirmation,
  /// cancellation and the consecutive-failure guard are what end a healthy
  /// run, and a pass count is not a duration.
  final int? maxPasses;

  /// Longest wait for a share whose status check is still ahead. Vizor
  /// refreshes round state on its own schedule, so it lifts the SDK's
  /// 30-second heartbeat cap rather than waking to find nothing ready.
  final BigInt? futureCheckMaxDelaySeconds;

  const ApiShareTrackingDrivePolicy({
    this.failureRetrySeconds,
    this.maxConsecutiveFailures,
    this.maxPasses,
    this.futureCheckMaxDelaySeconds,
  });

  @override
  int get hashCode =>
      failureRetrySeconds.hashCode ^
      maxConsecutiveFailures.hashCode ^
      maxPasses.hashCode ^
      futureCheckMaxDelaySeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiShareTrackingDrivePolicy &&
          runtimeType == other.runtimeType &&
          failureRetrySeconds == other.failureRetrySeconds &&
          maxConsecutiveFailures == other.maxConsecutiveFailures &&
          maxPasses == other.maxPasses &&
          futureCheckMaxDelaySeconds == other.futureCheckMaxDelaySeconds;
}

/// One observation from a tracking run, or its single terminal report.
///
/// Exactly one `Result`-kind event is emitted however the run ends, carrying
/// either the report or a bridge error.
class ApiShareTrackingRunEvent {
  final ApiRoundStepEventKind kind;
  final ShareTrackingEventView? event;
  final ShareTrackingRunReportView? report;
  final ApiRoundStepError? error;

  const ApiShareTrackingRunEvent({
    required this.kind,
    this.event,
    this.report,
    this.error,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ event.hashCode ^ report.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiShareTrackingRunEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          event == other.event &&
          report == other.report &&
          error == other.error;
}
