// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/zcash_voting/config.dart';
import '../third_party/zcash_voting/delegate.dart';
import '../third_party/zcash_voting/share_policy.dart';
import '../third_party/zcash_voting/wire.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `catch`, `config_error`, `delegation_static_inputs_for`, `internal`, `invalid_input`, `pir_snapshot_failure`, `pir_snapshot_height_field`, `pir_snapshot_probe_attempt`, `pir_snapshot_root_url`, `probe_pir_snapshot_endpoint`, `round_inputs`, `view`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PirSnapshotProbeAttempt`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

/// Supplies the disposable local chain anchor for regtest integration tests.
/// This does not change mainnet/testnet trust or verification rules.
Future<void> configureRegtestVotingParticipation({
  required String chainId,
  required String validatorHash,
}) => RustLib.instance.api.crateApiVotingConfigureRegtestVotingParticipation(
  chainId: chainId,
  validatorHash: validatorHash,
);

/// UFVK-only preparation for read-only participation discovery (also Keystone).
Future<String> prepareVotingParticipation({
  required ApiVotingRoundContext ctx,
}) => RustLib.instance.api.crateApiVotingPrepareVotingParticipation(ctx: ctx);

/// Verify consensus/storage evidence and evaluate the remaining snapshot notes.
Future<String> evaluateVotingParticipation({
  required ApiVotingRoundContext ctx,
  required String fingerprint,
  required String evidence,
  required PlatformInt64 nowSeconds,
}) => RustLib.instance.api.crateApiVotingEvaluateVotingParticipation(
  ctx: ctx,
  fingerprint: fingerprint,
  evidence: evidence,
  nowSeconds: nowSeconds,
);

/// Probe every configured PIR endpoint and select one at the round's height.
///
/// Probing runs here rather than in Dart so the wallet has one PIR resolution
/// path instead of a probe on one side of the bridge and the selection policy
/// on the other. Traffic uses the routed transport, so the probe follows the
/// same network route as the rest of the wallet's foreground voting traffic.
///
/// Returns `endpoint: None` when endpoints were probed but none served the
/// round's snapshot height; that is a normal, recoverable outcome the caller
/// reports from the diagnostics. An empty `endpoints` list is an error,
/// because it means the round is misconfigured rather than the fleet behind.
Future<ApiPirSnapshotResolution> resolvePirSnapshotEndpoint({
  required List<String> endpoints,
  required BigInt expectedSnapshotHeight,
}) => RustLib.instance.api.crateApiVotingResolvePirSnapshotEndpoint(
  endpoints: endpoints,
  expectedSnapshotHeight: expectedSnapshotHeight,
);

/// Return the shared last-moment helper-share buffer, in Unix seconds.
BigInt? lastMomentBufferSeconds({
  required BigInt ceremonyStartSeconds,
  required BigInt voteEndTimeSeconds,
}) => RustLib.instance.api.crateApiVotingLastMomentBufferSeconds(
  ceremonyStartSeconds: ceremonyStartSeconds,
  voteEndTimeSeconds: voteEndTimeSeconds,
);

/// Return true when `now_seconds` is inside the active round's last-moment window.
bool isLastMoment({
  required BigInt nowSeconds,
  required BigInt ceremonyStartSeconds,
  required BigInt voteEndTimeSeconds,
}) => RustLib.instance.api.crateApiVotingIsLastMoment(
  nowSeconds: nowSeconds,
  ceremonyStartSeconds: ceremonyStartSeconds,
  voteEndTimeSeconds: voteEndTimeSeconds,
);

/// Returns the proposal id range the pinned SDK enforces.
Future<ApiProposalIdRange> votingProposalIdRange() =>
    RustLib.instance.api.crateApiVotingVotingProposalIdRange();

/// Build round params from server metadata while binding trusted `ea_pk`.
///
/// Trust model for the per-round parameters:
///
/// - `ea_pk` (the encryption-authority key votes are encrypted to) is the only
///   field that cannot be independently re-derived by the wallet, so it is
///   always sourced from the authenticated dynamic config and never from the
///   vote server's round response. This call ignores any server-supplied
///   `ea_pk` and substitutes the authenticated value for `round_id`.
/// - `snapshot_height` and `nc_root` are accepted from the server here but are
///   re-verified downstream against the wallet's own lightwalletd-synced
///   Orchard commitment tree: `zcash_voting`'s witness generation
///   (`validate_cached_tree_state_for_round`) requires the synced frontier
///   height and root to match these exactly, so a wrong value fails closed
///   before any vote material is produced.
/// - `nullifier_imt_root` is accepted from the server here but is used
///   downstream as the expected root that PIR nullifier proofs are verified
///   against; a wrong root makes proof verification fail closed rather than
///   enabling a forged non-membership claim.
///
/// In other words, every server-supplied field other than `ea_pk` is
/// cross-checked against an independent source (lightwalletd or PIR proofs)
/// downstream, and `ea_pk` is pinned to authenticated config here. A
/// compromised or stale endpoint therefore cannot steer voting to the wrong
/// authority or roots without being rejected.
Future<VotingRoundParams> trustedVotingRoundParamsFromConfig({
  required ResolvedVotingConfig resolvedConfig,
  required String roundId,
  required BigInt snapshotHeight,
  required List<int> ncRoot,
  required List<int> nullifierImtRoot,
}) => RustLib.instance.api.crateApiVotingTrustedVotingRoundParamsFromConfig(
  resolvedConfig: resolvedConfig,
  roundId: roundId,
  snapshotHeight: snapshotHeight,
  ncRoot: ncRoot,
  nullifierImtRoot: nullifierImtRoot,
);

/// Generate opaque voting hotkey bytes for a local voting account.
///
/// Vizor v2 uses the same random app-owned hotkey model for software and
/// Keystone accounts. The app persists this random per-round hotkey in secure
/// storage and reuses it for delegation setup and vote commitment signing.
Future<Uint8List> generateVotingHotkey({required String network}) =>
    RustLib.instance.api.crateApiVotingGenerateVotingHotkey(network: network);

/// Select notes and persist bundle rows for the delegation pipeline.
///
/// # Errors
///
/// Returns an error if bundle policy parsing, opening the sidecar DB, note
/// selection, or bundle setup fails.
Future<ApiBundleLayout> setupDelegationBundles({
  required ApiVotingRoundContext ctx,
}) => RustLib.instance.api.crateApiVotingSetupDelegationBundles(ctx: ctx);

/// Check whether the account has enough selected notes to vote in this round.
///
/// This selects notes at the round snapshot height and returns the smart-bundle
/// eligibility result without initializing round rows or persisting delegation
/// bundles.
///
/// # Errors
///
/// Returns an error if bundle policy parsing, opening the sidecar DB, note
/// selection, or eligibility calculation fails.
Future<ApiVotingEligibility> checkVotingEligibility({
  required ApiVotingRoundContext ctx,
}) => RustLib.instance.api.crateApiVotingCheckVotingEligibility(ctx: ctx);

/// Persist the snapshot-stable bundle plan and warm all bundle PIR inputs.
///
/// This is the vote-screen warm-up path. It requires an initialized round and
/// snapshot-selected notes, but no voting hotkey or wallet seed. The normal
/// prove path remains the correctness fallback for missing witnesses or PIR
/// cache rows.
Future<ApiSnapshotBundlePrecomputeResult> precomputeSnapshotBundles({
  required ApiVotingRoundContext ctx,
  required String pirServerUrl,
}) => RustLib.instance.api.crateApiVotingPrecomputeSnapshotBundles(
  ctx: ctx,
  pirServerUrl: pirServerUrl,
);

/// Generate and persist ZKP1 for one software delegation bundle without signing.
///
/// This is the account-bound continuation of snapshot PIR precompute. It uses
/// the stored app hotkey to prepare the bundle and persists the proof, but it
/// never receives the wallet mnemonic and cannot sign or submit a delegation.
/// Repeated calls reuse an existing proved, submitted, or confirmed bundle and
/// return `false`; a newly generated proof returns `true`.
///
/// # Errors
///
/// Returns an error if round inputs, hotkey validation, bundle preparation, PIR
/// access, or ZKP1 generation fails.
Future<bool> precomputeDelegationProof({
  required ApiVotingRoundContext ctx,
  required List<String> pirServerUrls,
  required List<int> storedHotkeySecret,
  required int bundleIndex,
}) => RustLib.instance.api.crateApiVotingPrecomputeDelegationProof(
  ctx: ctx,
  pirServerUrls: pirServerUrls,
  storedHotkeySecret: storedHotkeySecret,
  bundleIndex: bundleIndex,
);

/// Kick off process-lifetime Halo2 proving-key warm-up for voting proofs.
///
/// Safe to call repeatedly; only the first call starts work. Returns
/// immediately so Dart can overlap warm-up with PIR resolve / bundle setup.
void warmVotingProvingCaches() =>
    RustLib.instance.api.crateApiVotingWarmVotingProvingCaches();

/// Warm the bundle-independent PIR proof cache for one account and snapshot.
///
/// `keep_roots` is accepted for FRB compatibility; the SDK prunes cache rows
/// by age and does not take a keep list.
Future<ApiPirCacheWarmupResult> warmPirProofCache({
  required String dbPath,
  required String accountUuid,
  required String network,
  required String lightwalletdUrl,
  required BigInt snapshotHeight,
  required String pirServerUrl,
  required PirLayout pirLayout,
  required List<Uint8List> keepRoots,
}) => RustLib.instance.api.crateApiVotingWarmPirProofCache(
  dbPath: dbPath,
  accountUuid: accountUuid,
  network: network,
  lightwalletdUrl: lightwalletdUrl,
  snapshotHeight: snapshotHeight,
  pirServerUrl: pirServerUrl,
  pirLayout: pirLayout,
  keepRoots: keepRoots,
);

/// Build and redact voting PCZTs that Keystone can sign in one or more batches.
///
/// # Errors
///
/// Returns an error if bundle indexes are empty or duplicated, round input
/// resolution fails, or PCZT construction and redaction for any requested
/// bundle fails.
Future<List<KeystoneSigningRequest>> buildKeystoneDelegationRequests({
  required ApiVotingRoundContext ctx,
  required List<int> storedHotkeySecret,
  required List<int> bundleIndices,
}) => RustLib.instance.api.crateApiVotingBuildKeystoneDelegationRequests(
  ctx: ctx,
  storedHotkeySecret: storedHotkeySecret,
  bundleIndices: bundleIndices,
);

/// Atomically persist a batch of Keystone delegation signatures.
///
/// The SDK checks each tuple against the bundle's current sighash and
/// randomized key in the storage transaction, including idempotent retries.
/// Missing or replaced setup returns `KeystoneSignatureConflict`. Existing
/// matching tuples remain idempotent even when signature bytes differ, and any
/// validation or database error rolls back the complete batch.
Future<ApiKeystoneSignatureBatchResult> storeKeystoneSignaturesBatch({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required List<ApiKeystoneSignatureInput> signatures,
}) => RustLib.instance.api.crateApiVotingStoreKeystoneSignaturesBatch(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  signatures: signatures,
);

/// Load persisted Keystone signatures for one voting round.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails or signature rows cannot be
/// loaded.
Future<List<KeystoneSignatureRecord>> getKeystoneSignatures({
  required String dbPath,
  required String accountUuid,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetKeystoneSignatures(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Delete bundle rows at or above `keep_count` for partial-bundle recovery.
///
/// Returns the number of deleted rows.
Future<int> deleteSkippedBundles({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int keepCount,
}) => RustLib.instance.api.crateApiVotingDeleteSkippedBundles(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  keepCount: keepCount,
);

/// Sync vote commitment tree state for a voting round.
///
/// Returns the latest synced tree height. The underlying tree client is cached
/// per `(db_path, account_uuid)` so later VAN witness calls can reuse the synced
/// in-memory tree state.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails or tree sync against
/// `node_url` fails for `round_id`.
Future<int> syncVoteTree({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required String nodeUrl,
}) => RustLib.instance.api.crateApiVotingSyncVoteTree(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  nodeUrl: nodeUrl,
);

/// Clear process-local vote-tree sync state for a wallet or round.
///
/// Passing a non-empty round ID clears only that round's cached vote-tree sync
/// state by calling `zcash_voting::precompute::reset_vote_tree(db, round_id)`.
/// Passing `None` or an empty round ID performs account-wide vote-tree cleanup
/// with `zcash_voting::precompute::reset_vote_tree(db, "")`.
///
/// This does not clear unsigned delegation setup fields, delete durable recovery
/// rows, or abort in-flight proof/vote work already running on worker threads.
Future<void> resetVoteTree({
  required String dbPath,
  required String accountUuid,
  String? roundId,
}) => RustLib.instance.api.crateApiVotingResetVoteTree(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Clear process-local voting session state for a wallet or round.
///
/// Passing a non-empty round ID clears only that round's cached vote-tree sync
/// state and unsigned delegation setup fields by calling
/// `zcash_voting::precompute::reset_voting_session_state(db, round_id)`.
/// Passing `None` or an empty round ID performs account-wide vote-tree cleanup
/// with `zcash_voting::precompute::reset_voting_session_state(db, "")`.
///
/// This does not delete durable recovery rows or abort in-flight proof/vote
/// work already running on worker threads.
Future<void> resetVotingSessionState({
  required String dbPath,
  required String accountUuid,
  String? roundId,
}) => RustLib.instance.api.crateApiVotingResetVotingSessionState(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Delete all durable voting sidecar rows for an account.
///
/// This removes every persisted round scoped to `account_uuid`, relying on the
/// `zcash_voting` round deletion cascade for bundles, recovery rows, share
/// history, ballot intent, and cached tree state. It also deletes
/// round-independent `pir_proof_cache` rows for the same wallet id — browse-
/// only warm-up can persist those without ever creating a round. Use this only
/// at account deletion boundaries, not for ordinary voting-session retries.
Future<int> deleteVotingAccountState({
  required String dbPath,
  required String accountUuid,
}) => RustLib.instance.api.crateApiVotingDeleteVotingAccountState(
  dbPath: dbPath,
  accountUuid: accountUuid,
);

/// List rounds with durable unconfirmed helper shares for the given accounts.
///
/// Accounts with no pending rounds contribute nothing. The result is sorted by
/// account and round.
Future<List<ApiPendingShareRound>> listPendingShareRounds({
  required String dbPath,
  required List<String> accountUuids,
}) => RustLib.instance.api.crateApiVotingListPendingShareRounds(
  dbPath: dbPath,
  accountUuids: accountUuids,
);

/// Compute the resumable voting-session plan for a round. The plan reports the
/// ordered remaining work (`next_steps`) and which proposals are still open.
Future<RoundPlanView> getRoundPlan({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required List<int> proposalIds,
}) => RustLib.instance.api.crateApiVotingGetRoundPlan(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  proposalIds: proposalIds,
);

/// Authenticate the static voting config bytes and surface the dynamic mirrors.
///
/// The wallet fetches the static trust anchor with its own transport and passes
/// the bytes here. Rust verifies the hash pin and decodes the static config,
/// returning the ordered `dynamic_config_urls` the wallet must walk before
/// calling [`resolve_voting_config_from_attempts`].
///
/// The returned list is always non-empty. A v1 static config names exactly one
/// URL and yields a single entry, so the v1 path is unchanged; a v2 config
/// yields its full mirror list, canonical origin first. Config errors are
/// returned as a flat string.
Future<List<String>> resolveStaticVotingConfig({
  required String source,
  required List<int> staticBytes,
}) => RustLib.instance.api.crateApiVotingResolveStaticVotingConfig(
  source: source,
  staticBytes: staticBytes,
);

/// Resolve and authenticate voting config from wallet-fetched bytes.
///
/// The wallet owns transport: it fetches the static bytes, calls
/// [`resolve_static_voting_config`] to learn the dynamic mirrors, fetches them
/// in order, and passes the accumulated per-mirror outcomes here. Rust picks the
/// first mirror that both decodes and authenticates, reports the ones it passed
/// over, and computes the config-switch classification against `previous`.
///
/// Callers are expected to re-invoke this after each mirror fetch rather than
/// gathering every mirror up front, so a healthy primary costs one request. A
/// mirror that resolves but authenticates no rounds is deprioritized rather than
/// skipped, so the caller should keep walking while `authenticated_rounds` is
/// empty and accept the round-less resolution only once the list is exhausted.
///
/// Config errors are returned as a flat string; transport failures never reach
/// this layer, they arrive as failed attempts.
Future<VotingConfigResolution> resolveVotingConfigFromAttempts({
  required String source,
  required List<int> staticBytes,
  required List<ApiDynamicConfigAttempt> attempts,
  ResolvedVotingConfig? previous,
}) => RustLib.instance.api.crateApiVotingResolveVotingConfigFromAttempts(
  source: source,
  staticBytes: staticBytes,
  attempts: attempts,
  previous: previous,
);

/// Streams voting observability snapshots to Dart until the sink is closed.
///
/// Rust `log` records reach os_log, never the Flutter console, so a debugging
/// aid that lives only in `log stream` is invisible where developers actually
/// look. This is the second sink, not a replacement: os_log still receives
/// every line whether or not Dart ever registers.
///
/// Registering twice replaces the previous sink and closes it. Collection
/// itself stays governed by `VOTING_OBSERVABILITY_ENABLED`, so on a build with
/// observability off this stream is simply silent.
Stream<ApiVotingObservability> setVotingObservabilitySink() =>
    RustLib.instance.api.crateApiVotingSetVotingObservabilitySink();

/// Stops streaming snapshots to Dart, closing any registered sink.
Future<void> clearVotingObservabilitySink() =>
    RustLib.instance.api.crateApiVotingClearVotingObservabilitySink();

/// FRB-facing bundle layout for [`setup_delegation_bundles`].
///
/// Keeps the SDK's flat privacy-trim totals on the existing layout boundary so
/// Dart can surface withheld voting power without mirroring a nested policy.
class ApiBundleLayout {
  final int bundleCount;
  final BigInt eligibleWeight;
  final int droppedCount;
  final int privacyTrimDroppedBundles;
  final int privacyTrimDroppedNotes;
  final BigInt privacyTrimDroppedValueZatoshi;

  const ApiBundleLayout({
    required this.bundleCount,
    required this.eligibleWeight,
    required this.droppedCount,
    required this.privacyTrimDroppedBundles,
    required this.privacyTrimDroppedNotes,
    required this.privacyTrimDroppedValueZatoshi,
  });

  @override
  int get hashCode =>
      bundleCount.hashCode ^
      eligibleWeight.hashCode ^
      droppedCount.hashCode ^
      privacyTrimDroppedBundles.hashCode ^
      privacyTrimDroppedNotes.hashCode ^
      privacyTrimDroppedValueZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiBundleLayout &&
          runtimeType == other.runtimeType &&
          bundleCount == other.bundleCount &&
          eligibleWeight == other.eligibleWeight &&
          droppedCount == other.droppedCount &&
          privacyTrimDroppedBundles == other.privacyTrimDroppedBundles &&
          privacyTrimDroppedNotes == other.privacyTrimDroppedNotes &&
          privacyTrimDroppedValueZatoshi ==
              other.privacyTrimDroppedValueZatoshi;
}

/// One wallet-side fetch outcome for a single dynamic config mirror.
///
/// Flat by necessity: the crate's [`DynamicConfigAttempt`] carries a
/// `Result<Vec<u8>, String>`, which flutter_rust_bridge cannot represent as a
/// struct field. Exactly one of `bytes` / `error` is expected to be set;
/// `bytes: None` means this mirror did not produce usable bytes and `error`
/// explains why for logging and diagnostics.
class ApiDynamicConfigAttempt {
  final String url;
  final Uint8List? bytes;
  final String? error;

  const ApiDynamicConfigAttempt({required this.url, this.bytes, this.error});

  @override
  int get hashCode => url.hashCode ^ bytes.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDynamicConfigAttempt &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          bytes == other.bytes &&
          error == other.error;
}

/// A dynamic config mirror the resolver passed over, and why.
class ApiDynamicConfigMirrorFailure {
  final String url;
  final String reason;

  const ApiDynamicConfigMirrorFailure({
    required this.url,
    required this.reason,
  });

  @override
  int get hashCode => url.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDynamicConfigMirrorFailure &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          reason == other.reason;
}

/// Outcome of an idempotent Keystone signature batch write.
///
/// A tuple for a different signing context fails the whole batch with
/// `VotingError::KeystoneSignatureConflict`, which names the bundle.
class ApiKeystoneSignatureBatchResult {
  final int inserted;
  final int alreadyPresent;

  const ApiKeystoneSignatureBatchResult({
    required this.inserted,
    required this.alreadyPresent,
  });

  @override
  int get hashCode => inserted.hashCode ^ alreadyPresent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiKeystoneSignatureBatchResult &&
          runtimeType == other.runtimeType &&
          inserted == other.inserted &&
          alreadyPresent == other.alreadyPresent;
}

/// One Keystone delegation signature tuple to persist atomically.
class ApiKeystoneSignatureInput {
  final int bundleIndex;
  final Uint8List sig;
  final Uint8List sighash;
  final Uint8List rk;

  const ApiKeystoneSignatureInput({
    required this.bundleIndex,
    required this.sig,
    required this.sighash,
    required this.rk,
  });

  @override
  int get hashCode =>
      bundleIndex.hashCode ^ sig.hashCode ^ sighash.hashCode ^ rk.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiKeystoneSignatureInput &&
          runtimeType == other.runtimeType &&
          bundleIndex == other.bundleIndex &&
          sig == other.sig &&
          sighash == other.sighash &&
          rk == other.rk;
}

/// One account and round with durable unconfirmed helper shares.
class ApiPendingShareRound {
  final String accountUuid;
  final String roundId;
  final String? sessionJson;

  const ApiPendingShareRound({
    required this.accountUuid,
    required this.roundId,
    this.sessionJson,
  });

  @override
  int get hashCode =>
      accountUuid.hashCode ^ roundId.hashCode ^ sessionJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPendingShareRound &&
          runtimeType == other.runtimeType &&
          accountUuid == other.accountUuid &&
          roundId == other.roundId &&
          sessionJson == other.sessionJson;
}

/// FRB-facing outcome of the bundle-independent PIR proof cache warm-up.
class ApiPirCacheWarmupResult {
  /// Eligible notes selected at the snapshot height.
  final int noteCount;

  /// Nullifiers that already had a cached proof under the served root.
  final int cachedCount;

  /// Proofs fetched from the PIR server during this warm-up.
  final int fetchedCount;

  /// IMT root the PIR server served, as 32 little-endian bytes. Compare with
  /// the round's `nullifier_imt_root` to detect a stale snapshot.
  final Uint8List servedRoot;

  /// Cache rows evicted by automatic recency prune. Always `0` on this
  /// crate pin: `precompute_pir_proofs` prunes internally and does not
  /// report a count.
  final int prunedCount;

  const ApiPirCacheWarmupResult({
    required this.noteCount,
    required this.cachedCount,
    required this.fetchedCount,
    required this.servedRoot,
    required this.prunedCount,
  });

  @override
  int get hashCode =>
      noteCount.hashCode ^
      cachedCount.hashCode ^
      fetchedCount.hashCode ^
      servedRoot.hashCode ^
      prunedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPirCacheWarmupResult &&
          runtimeType == other.runtimeType &&
          noteCount == other.noteCount &&
          cachedCount == other.cachedCount &&
          fetchedCount == other.fetchedCount &&
          servedRoot == other.servedRoot &&
          prunedCount == other.prunedCount;
}

/// Selected PIR endpoint plus a diagnostic for every endpoint probed.
///
/// The full diagnostic set is part of the result, not debug output: the
/// delegation path builds its PIR failover list from the endpoints that
/// matched, and the status screen explains a failed resolution from the
/// heights the endpoints reported.
class ApiPirSnapshotResolution {
  /// `None` when every endpoint was probed and none matched the round.
  final String? endpoint;
  final List<PirSnapshotEndpointDiagnosticView> diagnostics;

  const ApiPirSnapshotResolution({this.endpoint, required this.diagnostics});

  @override
  int get hashCode => endpoint.hashCode ^ diagnostics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPirSnapshotResolution &&
          runtimeType == other.runtimeType &&
          endpoint == other.endpoint &&
          diagnostics == other.diagnostics;
}

/// Inclusive bounds the vote circuit enforces on an on-chain proposal id.
///
/// Exposed so hosts can check their own copy against the SDK rather than
/// discover a mismatch as a parse failure in front of a voter. Read from
/// `zcash_voting` directly, so bumping the pinned SDK moves this with it.
class ApiProposalIdRange {
  final int min;
  final int max;

  const ApiProposalIdRange({required this.min, required this.max});

  @override
  int get hashCode => min.hashCode ^ max.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiProposalIdRange &&
          runtimeType == other.runtimeType &&
          min == other.min &&
          max == other.max;
}

/// PIR cache result for one snapshot-precomputed delegation bundle.
class ApiSnapshotBundlePirResult {
  final int cachedCount;
  final int fetchedCount;

  const ApiSnapshotBundlePirResult({
    required this.cachedCount,
    required this.fetchedCount,
  });

  @override
  int get hashCode => cachedCount.hashCode ^ fetchedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSnapshotBundlePirResult &&
          runtimeType == other.runtimeType &&
          cachedCount == other.cachedCount &&
          fetchedCount == other.fetchedCount;
}

/// Snapshot bundle plan and PIR warm-up result exposed to Dart.
class ApiSnapshotBundlePrecomputeResult {
  final int bundleCount;
  final BigInt eligibleWeight;
  final int droppedCount;
  final int privacyTrimDroppedBundles;
  final int privacyTrimDroppedNotes;
  final BigInt privacyTrimDroppedValueZatoshi;
  final List<ApiSnapshotBundlePirResult> bundles;

  const ApiSnapshotBundlePrecomputeResult({
    required this.bundleCount,
    required this.eligibleWeight,
    required this.droppedCount,
    required this.privacyTrimDroppedBundles,
    required this.privacyTrimDroppedNotes,
    required this.privacyTrimDroppedValueZatoshi,
    required this.bundles,
  });

  @override
  int get hashCode =>
      bundleCount.hashCode ^
      eligibleWeight.hashCode ^
      droppedCount.hashCode ^
      privacyTrimDroppedBundles.hashCode ^
      privacyTrimDroppedNotes.hashCode ^
      privacyTrimDroppedValueZatoshi.hashCode ^
      bundles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSnapshotBundlePrecomputeResult &&
          runtimeType == other.runtimeType &&
          bundleCount == other.bundleCount &&
          eligibleWeight == other.eligibleWeight &&
          droppedCount == other.droppedCount &&
          privacyTrimDroppedBundles == other.privacyTrimDroppedBundles &&
          privacyTrimDroppedNotes == other.privacyTrimDroppedNotes &&
          privacyTrimDroppedValueZatoshi ==
              other.privacyTrimDroppedValueZatoshi &&
          bundles == other.bundles;
}

/// Read-only minimum voting eligibility status for one round/account.
class ApiVotingEligibility {
  final bool isEligible;
  final int distinctNoteCount;
  final BigInt eligibleWeightZatoshi;

  /// Raw note value the privacy trim withholds from this round, not its
  /// bundle-quantized voting weight. Zero when nothing was withheld.
  final BigInt privacyTrimDroppedValueZatoshi;

  const ApiVotingEligibility({
    required this.isEligible,
    required this.distinctNoteCount,
    required this.eligibleWeightZatoshi,
    required this.privacyTrimDroppedValueZatoshi,
  });

  @override
  int get hashCode =>
      isEligible.hashCode ^
      distinctNoteCount.hashCode ^
      eligibleWeightZatoshi.hashCode ^
      privacyTrimDroppedValueZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingEligibility &&
          runtimeType == other.runtimeType &&
          isEligible == other.isEligible &&
          distinctNoteCount == other.distinctNoteCount &&
          eligibleWeightZatoshi == other.eligibleWeightZatoshi &&
          privacyTrimDroppedValueZatoshi ==
              other.privacyTrimDroppedValueZatoshi;
}

/// One SDK observability snapshot, flattened for codegen.
///
/// Mirrors [`crate::wallet::voting::observability::VotingObservabilitySnapshot`]
/// rather than re-exporting the SDK's types: those are `#[non_exhaustive]` and
/// nest `Vec`s of further structs, neither of which suits this surface.
/// `rendered` is the SDK's own `Display`, so a Dart line and its os_log
/// counterpart always say the same thing.
class ApiVotingObservability {
  /// The Vizor call site that asked, not the SDK operation.
  final String context;
  final String operation;
  final String? roundId;
  final String outcome;
  final BigInt elapsedUs;
  final BigInt startedAtUnixUs;
  final String rendered;

  /// One entry per record that failed, was rejected, or may have been
  /// dispatched, each carrying the SDK's stable `error_kind`. Empty on a
  /// clean run. `rendered` cannot show these: it prints summaries, and a
  /// summary has an outcome but no error category.
  final List<String> failures;

  const ApiVotingObservability({
    required this.context,
    required this.operation,
    this.roundId,
    required this.outcome,
    required this.elapsedUs,
    required this.startedAtUnixUs,
    required this.rendered,
    required this.failures,
  });

  @override
  int get hashCode =>
      context.hashCode ^
      operation.hashCode ^
      roundId.hashCode ^
      outcome.hashCode ^
      elapsedUs.hashCode ^
      startedAtUnixUs.hashCode ^
      rendered.hashCode ^
      failures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingObservability &&
          runtimeType == other.runtimeType &&
          context == other.context &&
          operation == other.operation &&
          roundId == other.roundId &&
          outcome == other.outcome &&
          elapsedUs == other.elapsedUs &&
          startedAtUnixUs == other.startedAtUnixUs &&
          rendered == other.rendered &&
          failures == other.failures;
}

/// Shared delegation/voting round context passed across the FRB boundary.
///
/// This bundles the reusable round and wallet scope required by delegation setup,
/// proving, and keystone request flows.
class ApiVotingRoundContext {
  final String dbPath;
  final String lightwalletdUrl;
  final String network;
  final VotingRoundParams roundParams;
  final String roundName;
  final String? sessionJson;
  final String accountUuid;
  final int? maxRealNotesPerBundle;

  /// Authenticated PIR geometry expected from the selected endpoint.
  final PirLayout pirLayout;

  const ApiVotingRoundContext({
    required this.dbPath,
    required this.lightwalletdUrl,
    required this.network,
    required this.roundParams,
    required this.roundName,
    this.sessionJson,
    required this.accountUuid,
    this.maxRealNotesPerBundle,
    required this.pirLayout,
  });

  @override
  int get hashCode =>
      dbPath.hashCode ^
      lightwalletdUrl.hashCode ^
      network.hashCode ^
      roundParams.hashCode ^
      roundName.hashCode ^
      sessionJson.hashCode ^
      accountUuid.hashCode ^
      maxRealNotesPerBundle.hashCode ^
      pirLayout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingRoundContext &&
          runtimeType == other.runtimeType &&
          dbPath == other.dbPath &&
          lightwalletdUrl == other.lightwalletdUrl &&
          network == other.network &&
          roundParams == other.roundParams &&
          roundName == other.roundName &&
          sessionJson == other.sessionJson &&
          accountUuid == other.accountUuid &&
          maxRealNotesPerBundle == other.maxRealNotesPerBundle &&
          pirLayout == other.pirLayout;
}

class VotingConfigResolution {
  final ResolvedVotingConfig config;
  final ConfigSwitchKind switchKind;

  /// Mirrors skipped before the one that resolved. Empty on the happy path.
  final List<ApiDynamicConfigMirrorFailure> skippedMirrors;

  const VotingConfigResolution({
    required this.config,
    required this.switchKind,
    required this.skippedMirrors,
  });

  @override
  int get hashCode =>
      config.hashCode ^ switchKind.hashCode ^ skippedMirrors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VotingConfigResolution &&
          runtimeType == other.runtimeType &&
          config == other.config &&
          switchKind == other.switchKind &&
          skippedMirrors == other.skippedMirrors;
}
