// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/zcash_voting/config.dart';
import '../third_party/zcash_voting/delegate.dart';
import '../third_party/zcash_voting/share_policy.dart';
import '../third_party/zcash_voting/vote.dart';
import '../third_party/zcash_voting/wire.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_vote_commitments_result`, `catch`, `emit_signed_delegation_result`, `emit_signed_vote_result`, `helper_client`, `helper_delivery_db`, `is_cancelled`, `log_sink_closed`, `parse_tx_events_json`, `share_record`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `try_from`

/// Supplies the disposable local chain anchor for regtest integration tests.
/// This does not change mainnet/testnet trust or verification rules.
Future<void> configureRegtestVotingParticipation({
  required String chainId,
  required String validatorHash,
}) => RustLib.instance.api.crateApiVotingConfigureRegtestVotingParticipation(
  chainId: chainId,
  validatorHash: validatorHash,
);

/// UFVK-only preparation for read-only participation discovery (also Keystone).
Future<String> prepareVotingParticipation({
  required ApiVotingRoundContext ctx,
}) => RustLib.instance.api.crateApiVotingPrepareVotingParticipation(ctx: ctx);

/// Verify consensus/storage evidence and evaluate the remaining snapshot notes.
Future<String> evaluateVotingParticipation({
  required ApiVotingRoundContext ctx,
  required String fingerprint,
  required String evidence,
  required PlatformInt64 nowSeconds,
}) => RustLib.instance.api.crateApiVotingEvaluateVotingParticipation(
  ctx: ctx,
  fingerprint: fingerprint,
  evidence: evidence,
  nowSeconds: nowSeconds,
);

/// Select an exact-height PIR endpoint using the SDK's snapshot policy.
///
/// Dart owns probing and diagnostics because it owns the routed HTTP client.
/// The protocol decision about which diagnostics are eligible remains here.
String? selectPirSnapshotEndpoint({
  required List<ApiPirSnapshotEndpointDiagnostic> diagnostics,
  required BigInt expectedSnapshotHeight,
  required BigInt matchIndex,
}) => RustLib.instance.api.crateApiVotingSelectPirSnapshotEndpoint(
  diagnostics: diagnostics,
  expectedSnapshotHeight: expectedSnapshotHeight,
  matchIndex: matchIndex,
);

/// Return the shared last-moment helper-share buffer, in Unix seconds.
BigInt? lastMomentBufferSeconds({
  required BigInt ceremonyStartSeconds,
  required BigInt voteEndTimeSeconds,
}) => RustLib.instance.api.crateApiVotingLastMomentBufferSeconds(
  ceremonyStartSeconds: ceremonyStartSeconds,
  voteEndTimeSeconds: voteEndTimeSeconds,
);

/// Return true when `now_seconds` is inside the active round's last-moment window.
bool isLastMoment({
  required BigInt nowSeconds,
  required BigInt ceremonyStartSeconds,
  required BigInt voteEndTimeSeconds,
}) => RustLib.instance.api.crateApiVotingIsLastMoment(
  nowSeconds: nowSeconds,
  ceremonyStartSeconds: ceremonyStartSeconds,
  voteEndTimeSeconds: voteEndTimeSeconds,
);

/// Returns the vote-chain delegation submission body as validated wire JSON.
///
/// Binary fields are base64-encoded here so Dart does not duplicate protocol
/// field names or byte encoding rules.
Future<String> delegationSubmissionWireJson({
  required SignedDelegationPayloadView submission,
}) => RustLib.instance.api.crateApiVotingDelegationSubmissionWireJson(
  submission: submission,
);

/// Returns the vote-chain cast-vote submission body as validated wire JSON.
Future<String> voteCommitmentWireJson({
  required VoteCommitmentWire commitment,
}) => RustLib.instance.api.crateApiVotingVoteCommitmentWireJson(
  commitment: commitment,
);

/// Build round params from server metadata while binding trusted `ea_pk`.
///
/// Trust model for the per-round parameters:
///
/// - `ea_pk` (the encryption-authority key votes are encrypted to) is the only
///   field that cannot be independently re-derived by the wallet, so it is
///   always sourced from the authenticated dynamic config and never from the
///   vote server's round response. This call ignores any server-supplied
///   `ea_pk` and substitutes the authenticated value for `round_id`.
/// - `snapshot_height` and `nc_root` are accepted from the server here but are
///   re-verified downstream against the wallet's own lightwalletd-synced
///   Orchard commitment tree: `zcash_voting`'s witness generation
///   (`validate_cached_tree_state_for_round`) requires the synced frontier
///   height and root to match these exactly, so a wrong value fails closed
///   before any vote material is produced.
/// - `nullifier_imt_root` is accepted from the server here but is used
///   downstream as the expected root that PIR nullifier proofs are verified
///   against; a wrong root makes proof verification fail closed rather than
///   enabling a forged non-membership claim.
///
/// In other words, every server-supplied field other than `ea_pk` is
/// cross-checked against an independent source (lightwalletd or PIR proofs)
/// downstream, and `ea_pk` is pinned to authenticated config here. A
/// compromised or stale endpoint therefore cannot steer voting to the wrong
/// authority or roots without being rejected.
Future<VotingRoundParams> trustedVotingRoundParamsFromConfig({
  required ResolvedVotingConfig resolvedConfig,
  required String roundId,
  required BigInt snapshotHeight,
  required List<int> ncRoot,
  required List<int> nullifierImtRoot,
}) => RustLib.instance.api.crateApiVotingTrustedVotingRoundParamsFromConfig(
  resolvedConfig: resolvedConfig,
  roundId: roundId,
  snapshotHeight: snapshotHeight,
  ncRoot: ncRoot,
  nullifierImtRoot: nullifierImtRoot,
);

/// Creates helper delivery state for one account-and-round voting workflow.
VotingHelperDeliveryContext createVotingHelperDeliveryContext({
  required String dbPath,
  required String accountUuid,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingCreateVotingHelperDeliveryContext(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Creates one cancellable tracking-pass handle bound to its delivery context.
VotingShareTrackingPassHandle beginShareTrackingPass({
  required VotingHelperDeliveryContext context,
}) =>
    RustLib.instance.api.crateApiVotingBeginShareTrackingPass(context: context);

/// Canonicalizes and probes the complete configured helper fleet.
///
/// Validation happens before any request. The crate-owned helper client then
/// enforces canonical identity, response bounds, JSON content type, and the
/// progressive soft/hard readiness windows.
Future<ApiVotingHelperPreflight> preflightVotingHelpers({
  required VotingHelperDeliveryContext context,
  required List<String> configuredHelperUrls,
}) => RustLib.instance.api.crateApiVotingPreflightVotingHelpers(
  context: context,
  configuredHelperUrls: configuredHelperUrls,
);

/// Runs one confirm-or-retry pass over a round's unconfirmed helper shares.
///
/// This is the whole helper-facing workflow: the crate polls helpers, requires
/// matching confirmation responses from two distinct configured helpers,
/// persists confirmed shares, retries overdue shares against helpers that
/// missed them, and persists delivery outcomes. Dart owns only the timer and
/// cancellation triggers.
///
/// The sidecar write lock is held for the open (which may migrate) and then
/// released. Holding it across the pass would block user-initiated voting
/// writes for as long as helper polling takes; the writes this pass makes are
/// short and self-contained, and the sidecar runs in WAL mode with a busy
/// timeout.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails or a share record cannot be
/// read or updated. Helper failures are not errors: they are scored and
/// reported through the returned pass result.
Future<ApiShareTrackingReport> trackPendingShares({
  required VotingShareTrackingPassHandle passHandle,
  required List<String> configuredHelperUrls,
  required BigInt nowSeconds,
  BigInt? voteEndTimeSeconds,
}) => RustLib.instance.api.crateApiVotingTrackPendingShares(
  passHandle: passHandle,
  configuredHelperUrls: configuredHelperUrls,
  nowSeconds: nowSeconds,
  voteEndTimeSeconds: voteEndTimeSeconds,
);

/// Checks confirmation quorum for one known share without walking the round.
///
/// Foreground submission completion depends only on the designated immediate
/// share. Using the full recovery pass for that gate makes completion latency
/// scale with every proposal's delayed shares. This focused check polls at most
/// four configured helpers concurrently, persists confirmation after two
/// distinct helpers agree (or the sole helper in a one-helper fleet), and does
/// not resubmit or otherwise mutate unrelated shares.
Future<bool> confirmShareWithHelpers({
  required VotingShareTrackingPassHandle passHandle,
  required List<String> configuredHelperUrls,
  required int bundleIndex,
  required int proposalId,
  required int shareIndex,
  required BigInt nowSeconds,
}) => RustLib.instance.api.crateApiVotingConfirmShareWithHelpers(
  passHandle: passHandle,
  configuredHelperUrls: configuredHelperUrls,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  shareIndex: shareIndex,
  nowSeconds: nowSeconds,
);

/// Prepares and durably persists every helper-share placement for one vote.
///
/// Call this after the commitment has been persisted and before broadcasting
/// it to the vote chain. Repeating the call after restart reuses the exact plan;
/// it never starts helper network delivery.
///
/// # Errors
///
/// Returns an error without persisting a new plan if the helper fleet, proposal
/// roster, ballot intent, or committed-vote generation is invalid, or if the
/// database cannot be opened or updated.
Future<void> prepareCommittedShareDelivery({
  required VotingHelperDeliveryContext context,
  required int bundleIndex,
  required int proposalId,
  required ApiVotingHelperPreflight preflight,
  required BigInt nowSeconds,
  required BigInt voteEndTimeSeconds,
  BigInt? lastMomentBufferSeconds,
  required List<int> proposalIds,
}) => RustLib.instance.api.crateApiVotingPrepareCommittedShareDelivery(
  context: context,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  preflight: preflight,
  nowSeconds: nowSeconds,
  voteEndTimeSeconds: voteEndTimeSeconds,
  lastMomentBufferSeconds: lastMomentBufferSeconds,
  proposalIds: proposalIds,
);

/// Submits every incomplete share from an existing durable delivery plan.
///
/// Call this only after chain confirmation has been persisted. The SDK rebuilds
/// and validates every payload against the confirmed committed-vote generation
/// before the first POST, enforces its process-wide concurrency ceiling, and
/// journals each attempt before dispatch.
///
/// # Errors
///
/// Returns an error before network I/O if the plan is missing or incompatible,
/// the confirmed committed-vote generation is invalid, or the configured fleet
/// differs from the persisted plan. Helper refusals are scored and reported.
Future<ApiShareBatchDeliveryReport> submitPreparedSharesToHelpers({
  required VotingHelperDeliveryContext context,
  required int bundleIndex,
  required int proposalId,
  required List<String> configuredHelperUrls,
  required BigInt nowSeconds,
}) => RustLib.instance.api.crateApiVotingSubmitPreparedSharesToHelpers(
  context: context,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  configuredHelperUrls: configuredHelperUrls,
  nowSeconds: nowSeconds,
);

/// Return the next share-tracking delay in seconds using crate policy.
///
/// Vizor wakes the tracker when the next share reaches its status-check grace
/// boundary. The SDK's default policy caps future waits for wallets that also
/// use the tracking pass as a general heartbeat; Vizor refreshes round state
/// separately with a lightweight heartbeat and whenever the voting UI becomes
/// visible, so that cap would only cause redundant SQLite and helper passes.
Future<BigInt?> nextShareTrackingDelaySeconds({
  required List<ShareDelegationRecordView> shares,
  required BigInt nowSeconds,
}) => RustLib.instance.api.crateApiVotingNextShareTrackingDelaySeconds(
  shares: shares,
  nowSeconds: nowSeconds,
);

/// Generate opaque voting hotkey bytes for a local voting account.
///
/// Vizor v2 uses the same random app-owned hotkey model for software and
/// Keystone accounts. The app persists this random per-round hotkey in secure
/// storage and reuses it for delegation setup and vote commitment signing.
Future<Uint8List> generateVotingHotkey({required String network}) =>
    RustLib.instance.api.crateApiVotingGenerateVotingHotkey(network: network);

/// Select notes and persist bundle rows for the delegation pipeline.
///
/// Reuses existing bundle rows for the same round/wallet, so callers can safely
/// retry setup before proving a specific bundle.
///
/// # Errors
///
/// Returns an error if bundle policy parsing, opening the sidecar DB, round
/// initialization, note selection, or bundle layout persistence fails.
Future<ApiBundleLayout> setupDelegationBundles({
  required ApiVotingRoundContext ctx,
}) => RustLib.instance.api.crateApiVotingSetupDelegationBundles(ctx: ctx);

/// Check whether the account has enough selected notes to vote in this round.
///
/// This selects notes at the round snapshot height and returns the smart-bundle
/// eligibility result without initializing round rows or persisting delegation
/// bundles.
///
/// # Errors
///
/// Returns an error if bundle policy parsing, opening the sidecar DB, note
/// selection, or eligibility calculation fails.
Future<ApiVotingEligibility> checkVotingEligibility({
  required ApiVotingRoundContext ctx,
}) => RustLib.instance.api.crateApiVotingCheckVotingEligibility(ctx: ctx);

/// Persist the snapshot-stable bundle plan and warm all bundle PIR inputs.
///
/// This is the vote-screen warm-up path. It requires an initialized round and
/// snapshot-selected notes, but no voting hotkey or wallet seed. The normal
/// prove path remains the correctness fallback for missing witnesses or PIR
/// cache rows.
Future<ApiSnapshotBundlePrecomputeResult> precomputeSnapshotBundles({
  required ApiVotingRoundContext ctx,
  required String pirServerUrl,
}) => RustLib.instance.api.crateApiVotingPrecomputeSnapshotBundles(
  ctx: ctx,
  pirServerUrl: pirServerUrl,
);

/// Build delegation PCZT material and prefetch/cache PIR-backed IMT proofs.
///
/// This is a background warm-up path. The normal proof path still fetches any
/// missing PIR proofs if this was not run or did not complete in time.
///
/// # Errors
///
/// Returns an error if round input resolution, hotkey validation, bundle
/// preparation, or PIR precompute fails.
Future<DelegationPirPrecomputeResultView> precomputeDelegationPir({
  required ApiVotingRoundContext ctx,
  required String pirServerUrl,
  required List<int> storedHotkeySecret,
  required int bundleIndex,
}) => RustLib.instance.api.crateApiVotingPrecomputeDelegationPir(
  ctx: ctx,
  pirServerUrl: pirServerUrl,
  storedHotkeySecret: storedHotkeySecret,
  bundleIndex: bundleIndex,
);

/// Generate and persist ZKP1 for one software delegation bundle without signing.
///
/// This is the account-bound continuation of snapshot PIR precompute. It uses
/// the stored app hotkey to prepare the bundle and persists the proof, but it
/// never receives the wallet mnemonic and cannot sign or submit a delegation.
/// Repeated calls reuse an existing proved, submitted, or confirmed bundle and
/// return `false`; a newly generated proof returns `true`.
///
/// # Errors
///
/// Returns an error if round inputs, hotkey validation, bundle preparation, PIR
/// access, or ZKP1 generation fails.
Future<bool> precomputeDelegationProof({
  required ApiVotingRoundContext ctx,
  required List<String> pirServerUrls,
  required List<int> storedHotkeySecret,
  required int bundleIndex,
}) => RustLib.instance.api.crateApiVotingPrecomputeDelegationProof(
  ctx: ctx,
  pirServerUrls: pirServerUrls,
  storedHotkeySecret: storedHotkeySecret,
  bundleIndex: bundleIndex,
);

/// Kick off process-lifetime Halo2 proving-key warm-up for voting proofs.
///
/// Safe to call repeatedly; only the first call starts work. Returns
/// immediately so Dart can overlap warm-up with PIR resolve / bundle setup.
void warmVotingProvingCaches() =>
    RustLib.instance.api.crateApiVotingWarmVotingProvingCaches();

/// Warm the bundle-independent PIR proof cache for one account.
///
/// Fetches and caches IMT non-membership proofs for the account's eligible
/// notes at `snapshot_height` against whatever snapshot the PIR endpoint
/// currently serves. Notes are planned with the same whale-protected default
/// bundle policy round setup uses. The library prunes cache rows older than
/// four weeks; `keep_roots` is accepted for FRB compatibility.
///
/// This is a background warm-up path: it needs no hotkey, no round rows, and
/// no bundles, so it can run as soon as the wallet is scanned to the snapshot
/// height. The delegation prove path reads the same cache and still fetches
/// anything missing, so skipping or failing this call only costs latency.
///
/// # Errors
///
/// Returns an error if the network string is invalid, the sidecar cannot be
/// opened, the wallet is not scanned to the snapshot height, note selection
/// fails, the PIR handshake fails, or a fetched proof does not verify.
Future<ApiPirCacheWarmupResult> warmPirProofCache({
  required String dbPath,
  required String accountUuid,
  required String network,
  required String lightwalletdUrl,
  required BigInt snapshotHeight,
  required String pirServerUrl,
  required PirLayout pirLayout,
  required List<Uint8List> keepRoots,
}) => RustLib.instance.api.crateApiVotingWarmPirProofCache(
  dbPath: dbPath,
  accountUuid: accountUuid,
  network: network,
  lightwalletdUrl: lightwalletdUrl,
  snapshotHeight: snapshotHeight,
  pirServerUrl: pirServerUrl,
  pirLayout: pirLayout,
  keepRoots: keepRoots,
);

/// Streaming variant of `build_prove_and_sign_delegation_payload`.
///
/// Emits local preparation phase events while work progresses, then emits a
/// final `"result"` event containing `SignedDelegationPayloadView`. The function
/// returns `Ok(())` after the terminal event is queued. `pir_server_urls` must
/// contain at least one endpoint that serves the round's exact snapshot; later
/// entries are used only after retryable PIR transport failures.
///
/// # Errors
///
/// Returns an error if round input resolution fails before the stream work
/// starts. Runtime delegation/proving errors are forwarded into the sink as
/// stream errors.
Stream<ApiDelegationProofEvent> buildProveAndSignDelegationPayloadWithProgress({
  required ApiVotingRoundContext ctx,
  required List<String> pirServerUrls,
  required String mnemonic,
  required List<int> storedHotkeySecret,
  required int bundleIndex,
}) => RustLib.instance.api
    .crateApiVotingBuildProveAndSignDelegationPayloadWithProgress(
      ctx: ctx,
      pirServerUrls: pirServerUrls,
      mnemonic: mnemonic,
      storedHotkeySecret: storedHotkeySecret,
      bundleIndex: bundleIndex,
    );

/// Build and redact voting PCZTs that Keystone can sign in one or more batches.
///
/// # Errors
///
/// Returns an error if bundle indexes are empty or duplicated, round input
/// resolution fails, or PCZT construction and redaction for any requested
/// bundle fails.
Future<List<KeystoneSigningRequest>> buildKeystoneDelegationRequests({
  required ApiVotingRoundContext ctx,
  required List<int> storedHotkeySecret,
  required List<int> bundleIndices,
}) => RustLib.instance.api.crateApiVotingBuildKeystoneDelegationRequests(
  ctx: ctx,
  storedHotkeySecret: storedHotkeySecret,
  bundleIndices: bundleIndices,
);

/// Persist a Keystone signature for one delegation bundle.
///
/// # Errors
///
/// Returns an error if signature lengths are invalid, opening the voting DB
/// fails, or persisting the signature record fails.
Future<void> storeKeystoneSignature({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required List<int> sig,
  required List<int> sighash,
  required List<int> rk,
}) => RustLib.instance.api.crateApiVotingStoreKeystoneSignature(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  sig: sig,
  sighash: sighash,
  rk: rk,
);

/// Atomically persist a batch of Keystone delegation signatures.
///
/// Existing tuples for the same sighash and randomized key are accepted as
/// idempotent retries, even when randomized signing produced different valid
/// signature bytes. A tuple for a different signing context is a conflict, and
/// any validation or database error rolls back the complete batch.
Future<ApiKeystoneSignatureBatchResult> storeKeystoneSignaturesBatch({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required List<ApiKeystoneSignatureInput> signatures,
}) => RustLib.instance.api.crateApiVotingStoreKeystoneSignaturesBatch(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  signatures: signatures,
);

/// Load persisted Keystone signatures for one voting round.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails or signature rows cannot be
/// loaded.
Future<List<KeystoneSignatureRecord>> getKeystoneSignatures({
  required String dbPath,
  required String accountUuid,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetKeystoneSignatures(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Streaming Keystone variant of `build_prove_and_sign_delegation_payload`.
/// `pir_server_urls` follows the same exact-snapshot failover contract.
///
/// # Errors
///
/// Returns an error if round input resolution fails before stream work starts.
/// Runtime proving/signature errors are emitted through the sink.
Stream<ApiDelegationProofEvent>
buildProveDelegationPayloadWithKeystoneSignatureWithProgress({
  required ApiVotingRoundContext ctx,
  required List<String> pirServerUrls,
  required List<int> storedHotkeySecret,
  required int bundleIndex,
  required List<int> keystoneSig,
  required List<int> keystoneSighash,
}) => RustLib.instance.api
    .crateApiVotingBuildProveDelegationPayloadWithKeystoneSignatureWithProgress(
      ctx: ctx,
      pirServerUrls: pirServerUrls,
      storedHotkeySecret: storedHotkeySecret,
      bundleIndex: bundleIndex,
      keystoneSig: keystoneSig,
      keystoneSighash: keystoneSighash,
    );

/// Record a submitted delegation transaction hash for one bundle.
///
/// Repeated calls are idempotent only for the same transaction hash.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the bundle key is missing,
/// or the stored hash conflicts with `tx_hash`.
Future<void> markDelegationSubmitted({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required String txHash,
}) => RustLib.instance.api.crateApiVotingMarkDelegationSubmitted(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  txHash: txHash,
);

/// Parse tx events and record a confirmed delegation submission.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the event payload does not
/// match the expected round/type shape, or confirmation state cannot be stored.
Future<DelegationConfirmation> confirmDelegationSubmission({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required String txHash,
  required String eventsJson,
}) => RustLib.instance.api.crateApiVotingConfirmDelegationSubmission(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  txHash: txHash,
  eventsJson: eventsJson,
);

/// Delete bundle rows at or above `keep_count` for partial-bundle recovery.
///
/// Returns the number of deleted rows.
Future<int> deleteSkippedBundles({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int keepCount,
}) => RustLib.instance.api.crateApiVotingDeleteSkippedBundles(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  keepCount: keepCount,
);

/// Sync vote commitment tree state for a voting round.
///
/// Returns the latest synced tree height. The underlying tree client is cached
/// per `(db_path, account_uuid)` so later VAN witness calls can reuse the synced
/// in-memory tree state.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails or tree sync against
/// `node_url` fails for `round_id`.
Future<int> syncVoteTree({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required String nodeUrl,
}) => RustLib.instance.api.crateApiVotingSyncVoteTree(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  nodeUrl: nodeUrl,
);

/// Generate a Vote Authority Note Merkle witness for a delegation bundle.
///
/// `anchor_height` is the vote-tree height where the witness should be anchored;
/// callers must sync the same round before requesting the witness.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, `bundle_index` is out of
/// range for the round, or witness generation fails.
Future<VanWitness> generateVanWitness({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int anchorHeight,
}) => RustLib.instance.api.crateApiVotingGenerateVanWitness(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  anchorHeight: anchorHeight,
);

/// Clear process-local vote-tree sync state for a wallet or round.
///
/// Passing a non-empty round ID clears only that round's cached vote-tree sync
/// state by calling `zcash_voting::precompute::reset_vote_tree(db, round_id)`.
/// Passing `None` or an empty round ID performs account-wide vote-tree cleanup
/// with `zcash_voting::precompute::reset_vote_tree(db, "")`.
///
/// This does not clear unsigned delegation setup fields, delete durable recovery
/// rows, or abort in-flight proof/vote work already running on worker threads.
Future<void> resetVoteTree({
  required String dbPath,
  required String accountUuid,
  String? roundId,
}) => RustLib.instance.api.crateApiVotingResetVoteTree(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Clear process-local voting session state for a wallet or round.
///
/// Passing a non-empty round ID clears only that round's cached vote-tree sync
/// state and unsigned delegation setup fields by calling
/// `zcash_voting::precompute::reset_voting_session_state(db, round_id)`.
/// Passing `None` or an empty round ID performs account-wide vote-tree cleanup
/// with `zcash_voting::precompute::reset_voting_session_state(db, "")`.
///
/// This does not delete durable recovery rows or abort in-flight proof/vote
/// work already running on worker threads.
Future<void> resetVotingSessionState({
  required String dbPath,
  required String accountUuid,
  String? roundId,
}) => RustLib.instance.api.crateApiVotingResetVotingSessionState(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Delete all durable voting sidecar rows for an account.
///
/// This removes every persisted round scoped to `account_uuid`, relying on the
/// `zcash_voting` round deletion cascade for bundles, recovery rows, share
/// history, ballot intent, and cached tree state. It also deletes
/// round-independent `pir_proof_cache` rows for the same wallet id — browse-
/// only warm-up can persist those without ever creating a round. Use this only
/// at account deletion boundaries, not for ordinary voting-session retries.
Future<int> deleteVotingAccountState({
  required String dbPath,
  required String accountUuid,
}) => RustLib.instance.api.crateApiVotingDeleteVotingAccountState(
  dbPath: dbPath,
  accountUuid: accountUuid,
);

/// Lists account/round pairs with durable unconfirmed helper shares.
///
/// The opaque session JSON is returned for caller-owned deadline checks. The
/// sidecar is not created when the wallet has never persisted voting state.
Future<List<ApiPendingShareRound>> listPendingShareRounds({
  required String dbPath,
  required List<String> accountUuids,
}) => RustLib.instance.api.crateApiVotingListPendingShareRounds(
  dbPath: dbPath,
  accountUuids: accountUuids,
);

/// Recover a committed but unsubmitted vote from persisted local recovery data.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, no matching commitment is
/// recoverable, or wire conversion fails.
Future<SignedVoteCommitmentsView> recoverVoteCommitment({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
}) => RustLib.instance.api.crateApiVotingRecoverVoteCommitment(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
);

/// Streaming variant of `build_vote_commitments`.
///
/// Emits per-proposal progress events, then a terminal `"result"` event carrying
/// `SignedVoteCommitmentsView`.
Stream<ApiVoteCommitEvent> buildVoteCommitmentsWithProgress({
  required String dbPath,
  required String accountUuid,
  required String network,
  required String roundId,
  required int bundleIndex,
  required List<int> storedHotkeySecret,
  required VanWitness vanWitness,
  required List<DraftVote> draftVotes,
}) => RustLib.instance.api.crateApiVotingBuildVoteCommitmentsWithProgress(
  dbPath: dbPath,
  accountUuid: accountUuid,
  network: network,
  roundId: roundId,
  bundleIndex: bundleIndex,
  storedHotkeySecret: storedHotkeySecret,
  vanWitness: vanWitness,
  draftVotes: draftVotes,
);

/// Load the full recovery/share-tracking summary for one voting round.
Future<RoundRecoveryStateView> getRoundRecoveryState({
  required String dbPath,
  required String accountUuid,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetRoundRecoveryState(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Record a submitted cast-vote transaction hash for one bundle/proposal key.
///
/// Repeated calls are idempotent only for the same transaction hash.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the vote key is missing, or
/// the stored hash conflicts with `tx_hash`.
Future<void> markVoteSubmitted({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required String txHash,
}) => RustLib.instance.api.crateApiVotingMarkVoteSubmitted(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  txHash: txHash,
);

/// Parse tx events and record a confirmed vote submission.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the event payload does not
/// match the expected round/type shape, or confirmation state cannot be stored.
Future<VoteConfirmation> confirmVoteSubmission({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required String txHash,
  required String eventsJson,
}) => RustLib.instance.api.crateApiVotingConfirmVoteSubmission(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  txHash: txHash,
  eventsJson: eventsJson,
);

/// Compute the resumable voting-session plan for a round. The plan reports the
/// ordered remaining work (`next_steps`) and which proposals are still open.
Future<RoundPlanView> getRoundPlan({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required List<int> proposalIds,
}) => RustLib.instance.api.crateApiVotingGetRoundPlan(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  proposalIds: proposalIds,
);

/// Persist (insert or replace) the voter's ballot intent for one proposal.
/// Pass `skipped: true` for `Decision::Skipped`; otherwise `choice` must be set.
/// `num_options` is the proposal's declared option count.
Future<void> setBallotIntent({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int proposalId,
  required int numOptions,
  required bool skipped,
  int? choice,
}) => RustLib.instance.api.crateApiVotingSetBallotIntent(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  proposalId: proposalId,
  numOptions: numOptions,
  skipped: skipped,
  choice: choice,
);

/// Authenticate the static voting config bytes and surface the dynamic mirrors.
///
/// The wallet fetches the static trust anchor with its own transport and passes
/// the bytes here. Rust verifies the hash pin and decodes the static config,
/// returning the ordered `dynamic_config_urls` the wallet must walk before
/// calling [`resolve_voting_config_from_attempts`].
///
/// The returned list is always non-empty. A v1 static config names exactly one
/// URL and yields a single entry, so the v1 path is unchanged; a v2 config
/// yields its full mirror list, canonical origin first. Config errors are
/// returned as a flat string.
Future<List<String>> resolveStaticVotingConfig({
  required String source,
  required List<int> staticBytes,
}) => RustLib.instance.api.crateApiVotingResolveStaticVotingConfig(
  source: source,
  staticBytes: staticBytes,
);

/// Resolve and authenticate voting config from wallet-fetched bytes.
///
/// The wallet owns transport: it fetches the static bytes, calls
/// [`resolve_static_voting_config`] to learn the dynamic mirrors, fetches them
/// in order, and passes the accumulated per-mirror outcomes here. Rust picks the
/// first mirror that both decodes and authenticates, reports the ones it passed
/// over, and computes the config-switch classification against `previous`.
///
/// Callers are expected to re-invoke this after each mirror fetch rather than
/// gathering every mirror up front, so a healthy primary costs one request. A
/// mirror that resolves but authenticates no rounds is deprioritized rather than
/// skipped, so the caller should keep walking while `authenticated_rounds` is
/// empty and accept the round-less resolution only once the list is exhausted.
///
/// Config errors are returned as a flat string; transport failures never reach
/// this layer, they arrive as failed attempts.
Future<VotingConfigResolution> resolveVotingConfigFromAttempts({
  required String source,
  required List<int> staticBytes,
  required List<ApiDynamicConfigAttempt> attempts,
  ResolvedVotingConfig? previous,
}) => RustLib.instance.api.crateApiVotingResolveVotingConfigFromAttempts(
  source: source,
  staticBytes: staticBytes,
  attempts: attempts,
  previous: previous,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VotingHelperDeliveryContext>>
abstract class VotingHelperDeliveryContext implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VotingShareTrackingPassHandle>>
abstract class VotingShareTrackingPassHandle implements RustOpaqueInterface {
  /// Stops this tracking pass at its next cancellation check.
  void cancel();
}

/// FRB-facing bundle layout for [`setup_delegation_bundles`].
///
/// Keeps the SDK's flat privacy-trim totals on the existing layout boundary so
/// Dart can surface withheld voting power without mirroring a nested policy.
class ApiBundleLayout {
  final int bundleCount;
  final BigInt eligibleWeight;
  final int droppedCount;
  final int privacyTrimDroppedBundles;
  final int privacyTrimDroppedNotes;
  final BigInt privacyTrimDroppedValueZatoshi;

  const ApiBundleLayout({
    required this.bundleCount,
    required this.eligibleWeight,
    required this.droppedCount,
    required this.privacyTrimDroppedBundles,
    required this.privacyTrimDroppedNotes,
    required this.privacyTrimDroppedValueZatoshi,
  });

  @override
  int get hashCode =>
      bundleCount.hashCode ^
      eligibleWeight.hashCode ^
      droppedCount.hashCode ^
      privacyTrimDroppedBundles.hashCode ^
      privacyTrimDroppedNotes.hashCode ^
      privacyTrimDroppedValueZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiBundleLayout &&
          runtimeType == other.runtimeType &&
          bundleCount == other.bundleCount &&
          eligibleWeight == other.eligibleWeight &&
          droppedCount == other.droppedCount &&
          privacyTrimDroppedBundles == other.privacyTrimDroppedBundles &&
          privacyTrimDroppedNotes == other.privacyTrimDroppedNotes &&
          privacyTrimDroppedValueZatoshi ==
              other.privacyTrimDroppedValueZatoshi;
}

/// Progress event emitted while building, proving, and signing a delegation payload.
///
/// A terminal `"result"` event carries `signed_delegation_payload`; earlier
/// phase events only describe local preparation progress.
class ApiDelegationProofEvent {
  final String phase;
  final double? proofProgress;
  final SignedDelegationPayloadView? signedDelegationPayload;

  const ApiDelegationProofEvent({
    required this.phase,
    this.proofProgress,
    this.signedDelegationPayload,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      proofProgress.hashCode ^
      signedDelegationPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDelegationProofEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          proofProgress == other.proofProgress &&
          signedDelegationPayload == other.signedDelegationPayload;
}

/// One wallet-side fetch outcome for a single dynamic config mirror.
///
/// Flat by necessity: the crate's [`DynamicConfigAttempt`] carries a
/// `Result<Vec<u8>, String>`, which flutter_rust_bridge cannot represent as a
/// struct field. Exactly one of `bytes` / `error` is expected to be set;
/// `bytes: None` means this mirror did not produce usable bytes and `error`
/// explains why for logging and diagnostics.
class ApiDynamicConfigAttempt {
  final String url;
  final Uint8List? bytes;
  final String? error;

  const ApiDynamicConfigAttempt({required this.url, this.bytes, this.error});

  @override
  int get hashCode => url.hashCode ^ bytes.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDynamicConfigAttempt &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          bytes == other.bytes &&
          error == other.error;
}

/// A dynamic config mirror the resolver passed over, and why.
class ApiDynamicConfigMirrorFailure {
  final String url;
  final String reason;

  const ApiDynamicConfigMirrorFailure({
    required this.url,
    required this.reason,
  });

  @override
  int get hashCode => url.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDynamicConfigMirrorFailure &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          reason == other.reason;
}

/// Outcome of an idempotent Keystone signature batch write.
class ApiKeystoneSignatureBatchResult {
  final int inserted;
  final int alreadyPresent;
  final int? conflictingBundleIndex;

  const ApiKeystoneSignatureBatchResult({
    required this.inserted,
    required this.alreadyPresent,
    this.conflictingBundleIndex,
  });

  @override
  int get hashCode =>
      inserted.hashCode ^
      alreadyPresent.hashCode ^
      conflictingBundleIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiKeystoneSignatureBatchResult &&
          runtimeType == other.runtimeType &&
          inserted == other.inserted &&
          alreadyPresent == other.alreadyPresent &&
          conflictingBundleIndex == other.conflictingBundleIndex;
}

/// One Keystone delegation signature tuple to persist atomically.
class ApiKeystoneSignatureInput {
  final int bundleIndex;
  final Uint8List sig;
  final Uint8List sighash;
  final Uint8List rk;

  const ApiKeystoneSignatureInput({
    required this.bundleIndex,
    required this.sig,
    required this.sighash,
    required this.rk,
  });

  @override
  int get hashCode =>
      bundleIndex.hashCode ^ sig.hashCode ^ sighash.hashCode ^ rk.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiKeystoneSignatureInput &&
          runtimeType == other.runtimeType &&
          bundleIndex == other.bundleIndex &&
          sig == other.sig &&
          sighash == other.sighash &&
          rk == other.rk;
}

/// One account and round with durable unconfirmed helper shares.
class ApiPendingShareRound {
  final String accountUuid;
  final String roundId;
  final String? sessionJson;

  const ApiPendingShareRound({
    required this.accountUuid,
    required this.roundId,
    this.sessionJson,
  });

  @override
  int get hashCode =>
      accountUuid.hashCode ^ roundId.hashCode ^ sessionJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPendingShareRound &&
          runtimeType == other.runtimeType &&
          accountUuid == other.accountUuid &&
          roundId == other.roundId &&
          sessionJson == other.sessionJson;
}

/// FRB-facing outcome of the bundle-independent PIR proof cache warm-up.
class ApiPirCacheWarmupResult {
  /// Eligible notes selected at the snapshot height.
  final int noteCount;

  /// Nullifiers that already had a cached proof under the served root.
  final int cachedCount;

  /// Proofs fetched from the PIR server during this warm-up.
  final int fetchedCount;

  /// IMT root the PIR server served, as 32 little-endian bytes. Compare with
  /// the round's `nullifier_imt_root` to detect a stale snapshot.
  final Uint8List servedRoot;

  /// Cache rows evicted by automatic recency prune. Always `0` on this
  /// crate pin: `precompute_pir_proofs` prunes internally and does not
  /// report a count.
  final int prunedCount;

  const ApiPirCacheWarmupResult({
    required this.noteCount,
    required this.cachedCount,
    required this.fetchedCount,
    required this.servedRoot,
    required this.prunedCount,
  });

  @override
  int get hashCode =>
      noteCount.hashCode ^
      cachedCount.hashCode ^
      fetchedCount.hashCode ^
      servedRoot.hashCode ^
      prunedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPirCacheWarmupResult &&
          runtimeType == other.runtimeType &&
          noteCount == other.noteCount &&
          cachedCount == other.cachedCount &&
          fetchedCount == other.fetchedCount &&
          servedRoot == other.servedRoot &&
          prunedCount == other.prunedCount;
}

class ApiPirSnapshotEndpointDiagnostic {
  final String endpoint;
  final ApiPirSnapshotEndpointStatus status;
  final BigInt? reportedHeight;
  final int? httpStatusCode;
  final String? message;

  const ApiPirSnapshotEndpointDiagnostic({
    required this.endpoint,
    required this.status,
    this.reportedHeight,
    this.httpStatusCode,
    this.message,
  });

  @override
  int get hashCode =>
      endpoint.hashCode ^
      status.hashCode ^
      reportedHeight.hashCode ^
      httpStatusCode.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPirSnapshotEndpointDiagnostic &&
          runtimeType == other.runtimeType &&
          endpoint == other.endpoint &&
          status == other.status &&
          reportedHeight == other.reportedHeight &&
          httpStatusCode == other.httpStatusCode &&
          message == other.message;
}

enum ApiPirSnapshotEndpointStatus {
  matched,
  behind,
  ahead,
  missingHeight,
  malformedJson,
  nonSuccessStatus,
  timeoutOrNetworkError,
}

/// One share that reached a new helper during a tracking pass.
class ApiResubmittedShare {
  final ApiShareKey share;
  final String serverUrl;

  const ApiResubmittedShare({required this.share, required this.serverUrl});

  @override
  int get hashCode => share.hashCode ^ serverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiResubmittedShare &&
          runtimeType == other.runtimeType &&
          share == other.share &&
          serverUrl == other.serverUrl;
}

/// Commitment-wide helper delivery result.
class ApiShareBatchDeliveryReport {
  final List<ApiShareDeliveryOutcome> deliveries;
  final Uint32List pendingShareIndices;
  final bool cancelled;
  final bool legacyBestEffort;

  const ApiShareBatchDeliveryReport({
    required this.deliveries,
    required this.pendingShareIndices,
    required this.cancelled,
    required this.legacyBestEffort,
  });

  @override
  int get hashCode =>
      deliveries.hashCode ^
      pendingShareIndices.hashCode ^
      cancelled.hashCode ^
      legacyBestEffort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiShareBatchDeliveryReport &&
          runtimeType == other.runtimeType &&
          deliveries == other.deliveries &&
          pendingShareIndices == other.pendingShareIndices &&
          cancelled == other.cancelled &&
          legacyBestEffort == other.legacyBestEffort;
}

/// One share processed by commitment-wide initial delivery.
class ApiShareDeliveryOutcome {
  final int shareIndex;
  final ApiShareSubmissionReport submission;

  const ApiShareDeliveryOutcome({
    required this.shareIndex,
    required this.submission,
  });

  @override
  int get hashCode => shareIndex.hashCode ^ submission.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiShareDeliveryOutcome &&
          runtimeType == other.runtimeType &&
          shareIndex == other.shareIndex &&
          submission == other.submission;
}

/// One helper share identified within its round.
class ApiShareKey {
  final int bundleIndex;
  final int proposalId;
  final int shareIndex;

  const ApiShareKey({
    required this.bundleIndex,
    required this.proposalId,
    required this.shareIndex,
  });

  @override
  int get hashCode =>
      bundleIndex.hashCode ^ proposalId.hashCode ^ shareIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiShareKey &&
          runtimeType == other.runtimeType &&
          bundleIndex == other.bundleIndex &&
          proposalId == other.proposalId &&
          shareIndex == other.shareIndex;
}

/// Definite and outcome-unknown results from one initial helper fan-out.
class ApiShareSubmissionReport {
  /// Helpers that definitively accepted the share.
  final List<String> acceptedUrls;

  /// Helpers that may have accepted the share before the response failed.
  final List<String> ambiguousUrls;

  /// Desired number of definite helper placements.
  final int targetCount;

  const ApiShareSubmissionReport({
    required this.acceptedUrls,
    required this.ambiguousUrls,
    required this.targetCount,
  });

  @override
  int get hashCode =>
      acceptedUrls.hashCode ^ ambiguousUrls.hashCode ^ targetCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiShareSubmissionReport &&
          runtimeType == other.runtimeType &&
          acceptedUrls == other.acceptedUrls &&
          ambiguousUrls == other.ambiguousUrls &&
          targetCount == other.targetCount;
}

/// What one helper share-tracking pass did.
class ApiShareTrackingReport {
  /// Shares durably confirmed by the crate's two-helper quorum.
  final List<ApiShareKey> confirmed;

  /// Shares that reached an additional helper during this pass.
  final List<ApiResubmittedShare> resubmitted;

  /// Outcome-unknown attempts retained durably during this pass.
  final List<ApiResubmittedShare> ambiguous;

  /// Shares whose recovery material is missing, so no retry can help.
  final List<ApiShareKey> unrecoverable;

  /// True when the pass stopped early because Dart cancelled it.
  final bool cancelled;

  /// Seconds until the next pass, or `None` when nothing is pending.
  final BigInt? nextDelaySeconds;

  const ApiShareTrackingReport({
    required this.confirmed,
    required this.resubmitted,
    required this.ambiguous,
    required this.unrecoverable,
    required this.cancelled,
    this.nextDelaySeconds,
  });

  @override
  int get hashCode =>
      confirmed.hashCode ^
      resubmitted.hashCode ^
      ambiguous.hashCode ^
      unrecoverable.hashCode ^
      cancelled.hashCode ^
      nextDelaySeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiShareTrackingReport &&
          runtimeType == other.runtimeType &&
          confirmed == other.confirmed &&
          resubmitted == other.resubmitted &&
          ambiguous == other.ambiguous &&
          unrecoverable == other.unrecoverable &&
          cancelled == other.cancelled &&
          nextDelaySeconds == other.nextDelaySeconds;
}

/// PIR cache result for one snapshot-precomputed delegation bundle.
class ApiSnapshotBundlePirResult {
  final int cachedCount;
  final int fetchedCount;

  const ApiSnapshotBundlePirResult({
    required this.cachedCount,
    required this.fetchedCount,
  });

  @override
  int get hashCode => cachedCount.hashCode ^ fetchedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSnapshotBundlePirResult &&
          runtimeType == other.runtimeType &&
          cachedCount == other.cachedCount &&
          fetchedCount == other.fetchedCount;
}

/// Snapshot bundle plan and PIR warm-up result exposed to Dart.
class ApiSnapshotBundlePrecomputeResult {
  final int bundleCount;
  final BigInt eligibleWeight;
  final int droppedCount;
  final int privacyTrimDroppedBundles;
  final int privacyTrimDroppedNotes;
  final BigInt privacyTrimDroppedValueZatoshi;
  final List<ApiSnapshotBundlePirResult> bundles;

  const ApiSnapshotBundlePrecomputeResult({
    required this.bundleCount,
    required this.eligibleWeight,
    required this.droppedCount,
    required this.privacyTrimDroppedBundles,
    required this.privacyTrimDroppedNotes,
    required this.privacyTrimDroppedValueZatoshi,
    required this.bundles,
  });

  @override
  int get hashCode =>
      bundleCount.hashCode ^
      eligibleWeight.hashCode ^
      droppedCount.hashCode ^
      privacyTrimDroppedBundles.hashCode ^
      privacyTrimDroppedNotes.hashCode ^
      privacyTrimDroppedValueZatoshi.hashCode ^
      bundles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSnapshotBundlePrecomputeResult &&
          runtimeType == other.runtimeType &&
          bundleCount == other.bundleCount &&
          eligibleWeight == other.eligibleWeight &&
          droppedCount == other.droppedCount &&
          privacyTrimDroppedBundles == other.privacyTrimDroppedBundles &&
          privacyTrimDroppedNotes == other.privacyTrimDroppedNotes &&
          privacyTrimDroppedValueZatoshi ==
              other.privacyTrimDroppedValueZatoshi &&
          bundles == other.bundles;
}

/// Progress event emitted while building ZKP2 vote commitments.
///
/// A terminal `"result"` event carries the completed commitment set; earlier
/// phase events include the active `(proposal_id, bundle_index)` pair.
class ApiVoteCommitEvent {
  final String phase;
  final int? proposalId;
  final int? bundleIndex;
  final double? proofProgress;
  final SignedVoteCommitmentsView? commitments;

  const ApiVoteCommitEvent({
    required this.phase,
    this.proposalId,
    this.bundleIndex,
    this.proofProgress,
    this.commitments,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      proposalId.hashCode ^
      bundleIndex.hashCode ^
      proofProgress.hashCode ^
      commitments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVoteCommitEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          proposalId == other.proposalId &&
          bundleIndex == other.bundleIndex &&
          proofProgress == other.proofProgress &&
          commitments == other.commitments;
}

/// Read-only minimum voting eligibility status for one round/account.
class ApiVotingEligibility {
  final bool isEligible;
  final int distinctNoteCount;
  final BigInt eligibleWeightZatoshi;

  /// Raw note value the privacy trim withholds from this round, not its
  /// bundle-quantized voting weight. Zero when nothing was withheld.
  final BigInt privacyTrimDroppedValueZatoshi;

  const ApiVotingEligibility({
    required this.isEligible,
    required this.distinctNoteCount,
    required this.eligibleWeightZatoshi,
    required this.privacyTrimDroppedValueZatoshi,
  });

  @override
  int get hashCode =>
      isEligible.hashCode ^
      distinctNoteCount.hashCode ^
      eligibleWeightZatoshi.hashCode ^
      privacyTrimDroppedValueZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingEligibility &&
          runtimeType == other.runtimeType &&
          isEligible == other.isEligible &&
          distinctNoteCount == other.distinctNoteCount &&
          eligibleWeightZatoshi == other.eligibleWeightZatoshi &&
          privacyTrimDroppedValueZatoshi ==
              other.privacyTrimDroppedValueZatoshi;
}

/// Canonical helper fleet and readiness-ranked prefix for initial planning.
class ApiVotingHelperPreflight {
  /// Complete configured helper fleet in canonical caller order.
  final List<String> configuredHelperUrls;

  /// Ready helpers in the same relative order as the configured fleet.
  final List<String> readyHelperUrls;

  const ApiVotingHelperPreflight({
    required this.configuredHelperUrls,
    required this.readyHelperUrls,
  });

  @override
  int get hashCode => configuredHelperUrls.hashCode ^ readyHelperUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingHelperPreflight &&
          runtimeType == other.runtimeType &&
          configuredHelperUrls == other.configuredHelperUrls &&
          readyHelperUrls == other.readyHelperUrls;
}

/// Shared delegation/voting round context passed across the FRB boundary.
///
/// This bundles the reusable round and wallet scope required by delegation setup,
/// proving, and keystone request flows.
class ApiVotingRoundContext {
  final String dbPath;
  final String lightwalletdUrl;
  final String network;
  final VotingRoundParams roundParams;
  final String roundName;
  final String? sessionJson;
  final String accountUuid;
  final int? maxRealNotesPerBundle;

  /// Authenticated PIR geometry expected from the selected endpoint.
  final PirLayout pirLayout;

  const ApiVotingRoundContext({
    required this.dbPath,
    required this.lightwalletdUrl,
    required this.network,
    required this.roundParams,
    required this.roundName,
    this.sessionJson,
    required this.accountUuid,
    this.maxRealNotesPerBundle,
    required this.pirLayout,
  });

  @override
  int get hashCode =>
      dbPath.hashCode ^
      lightwalletdUrl.hashCode ^
      network.hashCode ^
      roundParams.hashCode ^
      roundName.hashCode ^
      sessionJson.hashCode ^
      accountUuid.hashCode ^
      maxRealNotesPerBundle.hashCode ^
      pirLayout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingRoundContext &&
          runtimeType == other.runtimeType &&
          dbPath == other.dbPath &&
          lightwalletdUrl == other.lightwalletdUrl &&
          network == other.network &&
          roundParams == other.roundParams &&
          roundName == other.roundName &&
          sessionJson == other.sessionJson &&
          accountUuid == other.accountUuid &&
          maxRealNotesPerBundle == other.maxRealNotesPerBundle &&
          pirLayout == other.pirLayout;
}

class VotingConfigResolution {
  final ResolvedVotingConfig config;
  final ConfigSwitchKind switchKind;

  /// Mirrors skipped before the one that resolved. Empty on the happy path.
  final List<ApiDynamicConfigMirrorFailure> skippedMirrors;

  const VotingConfigResolution({
    required this.config,
    required this.switchKind,
    required this.skippedMirrors,
  });

  @override
  int get hashCode =>
      config.hashCode ^ switchKind.hashCode ^ skippedMirrors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VotingConfigResolution &&
          runtimeType == other.runtimeType &&
          config == other.config &&
          switchKind == other.switchKind &&
          skippedMirrors == other.skippedMirrors;
}
