// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `encode`

/// Derive a public Base identity after checking the seed against the wallet DB.
Future<String> znsAccount({
  required String dbPath,
  required String network,
  required String accountUuid,
  required List<int> secretBytes,
}) => RustLib.instance.api.crateApiZnsZnsAccount(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  secretBytes: secretBytes,
);

/// Build only a supported, policy-bounded ZNS operation. No arbitrary call API.
Future<String> znsPrepare({
  required String network,
  required String configJson,
  required String owner,
  required String operationJson,
}) => RustLib.instance.api.crateApiZnsZnsPrepare(
  network: network,
  configJson: configJson,
  owner: owner,
  operationJson: operationJson,
);

/// Sign a supported ZNS intent using this software account's restored Base key.
Future<String> znsSign({
  required String dbPath,
  required String network,
  required String accountUuid,
  required List<int> secretBytes,
  required String configJson,
  required String operationJson,
  required String transactionJson,
}) => RustLib.instance.api.crateApiZnsZnsSign(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  secretBytes: secretBytes,
  configJson: configJson,
  operationJson: operationJson,
  transactionJson: transactionJson,
);

/// ZIP-316 decoding plus selected-network validation; transparent addresses fail.
Future<bool> znsValidateUnifiedAddress({
  required String network,
  required String address,
}) => RustLib.instance.api.crateApiZnsZnsValidateUnifiedAddress(
  network: network,
  address: address,
);

Future<String> znsReadCall({
  required String method,
  required String argsJson,
}) => RustLib.instance.api.crateApiZnsZnsReadCall(
  method: method,
  argsJson: argsJson,
);

Future<String> znsDecodeResult({
  required String method,
  required String data,
}) =>
    RustLib.instance.api.crateApiZnsZnsDecodeResult(method: method, data: data);

Future<String> znsRandomSecret() =>
    RustLib.instance.api.crateApiZnsZnsRandomSecret();
