#!/usr/bin/env python3
"""Inventory upstream files that changed in a Sybil fork.

This is a review aid for Apache License 2.0 section 4(b).  It reports the
files changed from an upstream tree, including tracked working changes by
default. It can add change notices to an explicit path list; it does not
decide whether a file is redistributable.
"""

from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys
ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE_EXTENSIONS = {
    ".c",
    ".cc",
    ".cpp",
    ".dart",
    ".h",
    ".hpp",
    ".java",
    ".js",
    ".kt",
    ".m",
    ".mm",
    ".php",
    ".py",
    ".ps1",
    ".rs",
    ".sh",
    ".swift",
    ".tsx",
    ".ts",
}
EXCLUDED_PREFIXES = {
    ".dart_tool/": "generated",
    "build/": "generated",
    "linux/flutter/": "generated",
    "macos/Flutter/": "generated",
    "scripts/zns/node_modules/": "vendored",
    "rust_builder/cargokit/": "vendored",
    "third_party/": "vendored",
    "windows/flutter/": "generated",
}
GENERATED_PATH_MARKERS = {
    "frb_generated": "generated",
    "generated_plugin": "generated",
}
SECTION_4B_MARKER = "Apache-2.0 section 4(b): modified from upstream by the Sybil fork."


def git(*args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or f"git {' '.join(args)} failed")
    return result.stdout


def changed_files(base: str, head: str) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    if head == "WORKTREE":
        diff_args = ("diff", "--name-status", "--diff-filter=AM", base, "--")
    else:
        diff_args = (
            "diff",
            "--name-status",
            "--diff-filter=AM",
            base,
            head,
            "--",
        )
    output = git(*diff_args)
    for line in output.splitlines():
        status, path = line.split("\t", 1)
        rows.append((status, path))
    return rows


def category(path: str) -> str:
    suffix = pathlib.PurePosixPath(path).suffix.lower()
    if suffix in SOURCE_EXTENSIONS:
        return "source"
    if suffix in {".cmake", ".gradle", ".kts", ".plist", ".xml", ".yaml", ".yml"}:
        return "build-or-metadata"
    if suffix in {".md", ".txt", ".csv", ".json"}:
        return "documentation-or-data"
    return "other"


def exclusion_reason(path: str) -> str | None:
    for prefix, reason in EXCLUDED_PREFIXES.items():
        if path.startswith(prefix):
            return reason
    for marker, reason in GENERATED_PATH_MARKERS.items():
        if marker in path:
            return reason
    if pathlib.PurePosixPath(path).suffix.lower() in SOURCE_EXTENSIONS:
        try:
            with (ROOT / path).open(encoding="utf-8") as source:
                start = source.read(4096)
            if "This file is automatically generated" in start or "@generated by" in start:
                return "generated"
        except (OSError, UnicodeError):
            return "unreadable"
    return None


def is_excluded(path: str) -> bool:
    return exclusion_reason(path) is not None


def has_change_notice(path: str) -> bool:
    try:
        content = (ROOT / path).read_text(encoding="utf-8", errors="replace")
    except (OSError, UnicodeError):
        return False
    first_lines = "\n".join(content.splitlines()[:40])
    return SECTION_4B_MARKER in first_lines


def render_markdown(base: str, head: str, rows: list[tuple[str, str]]) -> str:
    modified = [(status, path) for status, path in rows if status == "M"]
    additions = [(status, path) for status, path in rows if status == "A"]
    source_modified = [
        path
        for _, path in modified
        if category(path) == "source" and not is_excluded(path)
    ]
    provenance = (
        "committed Git history"
        if head != "WORKTREE"
        else "the upstream base and the current tracked working tree"
    )
    lines = [
        "# Apache modified-file inventory",
        "",
        f"This snapshot is generated from {provenance} for an owner-led",
        "Apache License 2.0 section 4(b) review. It does not add headers or make",
        "a copyright or redistribution decision. Re-run the tool after the fork",
        "or target feature set changes.",
        "",
        f"- Base: `{base}`",
        f"- Head: `{head}`",
        f"- Modified paths: {len(modified)}",
        f"- Added paths: {len(additions)}",
        f"- Source candidates among modified paths: {len(source_modified)}",
        "",
        "## Source modification-notice coverage",
        "",
        "The table reports the exact Sybil modification marker in each source file.",
        "Recheck the list after future upstream integration; files may be generated, vendored,",
        "or excluded from a particular target, and every existing upstream notice",
        "must be preserved. Inventory mode does not modify these files.",
        "",
        "| Path | Sybil modification marker in first 40 lines |",
        "| --- | --- |",
    ]
    for path in source_modified:
        state = "yes" if has_change_notice(path) else "no"
        lines.append(f"| `{path}` | {state} |")
    lines.extend(
        [
            "",
            "## Excluded source paths",
            "",
            "Generated and vendored source paths are shown separately so that an",
            "owner can make an explicit target decision. They are never passed",
            "to the opt-in header writer.",
            "",
            "| Path | Reason |",
            "| --- | --- |",
        ]
    )
    for _, path in modified:
        reason = exclusion_reason(path)
        if reason is not None and category(path) == "source":
            lines.append(f"| `{path}` | {reason} |")
    lines.extend(
        [
            "",
            "## Modified non-source paths",
            "",
            "These paths remain in the full inventory for review but are not",
            "proposed for a source-language header by this tool.",
            "",
            "| Path | Category |",
            "| --- | --- |",
        ]
    )
    for status, path in modified:
        if path not in source_modified:
            lines.append(f"| `{path}` | {category(path)} |")
    lines.extend(
        [
            "",
            "## Added paths",
            "",
            "Added files do not replace the section 4(b) review of modified",
            "upstream files. They still need an explicit rights-holder and license",
            "decision before distribution.",
            "",
            "| Path | Category |",
            "| --- | --- |",
        ]
    )
    for status, path in additions:
        reason = exclusion_reason(path)
        suffix = f" ({reason})" if reason is not None else ""
        lines.append(f"| `{path}` | {category(path)}{suffix} |")
    return "\n".join(lines) + "\n"


def render_tsv(base: str, head: str, rows: list[tuple[str, str]]) -> str:
    lines = ["status\tcategory\texcluded\tchange_notice_in_first_40_lines\tpath"]
    for status, path in rows:
        notice = "yes" if status == "M" and has_change_notice(path) else "no"
        excluded = "yes" if is_excluded(path) else "no"
        lines.append(f"{status}\t{category(path)}\t{excluded}\t{notice}\t{path}")
    return "\n".join(lines) + "\n"


def comment_prefix(path: str) -> str:
    suffix = pathlib.PurePosixPath(path).suffix.lower()
    if suffix in {".py", ".ps1", ".sh"}:
        return "#"
    if suffix in {
        ".c",
        ".cc",
        ".cpp",
        ".dart",
        ".h",
        ".hpp",
        ".java",
        ".js",
        ".kt",
        ".m",
        ".mm",
        ".php",
        ".rs",
        ".swift",
        ".ts",
        ".tsx",
    }:
        return "//"
    raise ValueError(f"No safe line-comment syntax for {path}")


def read_paths_file(path: pathlib.Path) -> list[str]:
    paths: list[str] = []
    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        relative = pathlib.PurePosixPath(line)
        if relative.is_absolute() or ".." in relative.parts:
            raise ValueError(f"Unsafe path at {path}:{line_number}: {line}")
        paths.append(line)
    if len(paths) != len(set(paths)):
        raise ValueError(f"Duplicate paths in {path}")
    return paths


def insert_change_notice(path: str) -> bool:
    target = ROOT / path
    content = target.read_bytes()
    if b"\0" in content:
        raise ValueError(f"Refusing binary file: {path}")
    text = content.decode("utf-8")
    if SECTION_4B_MARKER in "\n".join(text.splitlines()[:40]):
        return False

    prefix = comment_prefix(path)
    lines = text.splitlines(keepends=True)
    insertion_index = 0
    if lines and lines[0].startswith("#!"):
        insertion_index = 1
    if insertion_index < len(lines):
        stripped = lines[insertion_index].lstrip("\ufeff")
        if stripped.startswith("#") and "coding" in stripped:
            insertion_index += 1
    if insertion_index == 0 and lines and lines[0].startswith("\ufeff<?xml"):
        insertion_index = 1
    elif insertion_index == 0 and lines and lines[0].startswith("<?xml"):
        insertion_index = 1

    line_ending = "\r\n" if "\r\n" in text else "\n"
    notice = f"{prefix} {SECTION_4B_MARKER}{line_ending}"
    lines.insert(insertion_index, notice)
    target.write_text("".join(lines), encoding="utf-8", newline="")
    return True


def apply_change_notices(
    rows: list[tuple[str, str]], paths_file: pathlib.Path | None
) -> int:
    if paths_file is None:
        raise ValueError("--apply requires --paths-file with an explicit reviewed list")
    requested = read_paths_file(paths_file)
    eligible = {
        path
        for status, path in rows
        if status == "M" and category(path) == "source" and not is_excluded(path)
    }
    unknown = sorted(set(requested) - eligible)
    if unknown:
        raise ValueError(
            "paths are not eligible modified upstream source files: "
            + ", ".join(unknown)
        )
    changed = 0
    for path in requested:
        if insert_change_notice(path):
            changed += 1
    return changed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", default="upstream/main")
    parser.add_argument(
        "--head",
        default="WORKTREE",
        help="Git revision, or WORKTREE to include tracked staged/unstaged edits",
    )
    parser.add_argument("--format", choices=("markdown", "tsv"), default="markdown")
    parser.add_argument("--output", type=pathlib.Path)
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Apply the fixed change notice only to paths listed in --paths-file",
    )
    parser.add_argument("--paths-file", type=pathlib.Path)
    args = parser.parse_args()

    try:
        rows = changed_files(args.base, args.head)
        if args.apply:
            changed = apply_change_notices(rows, args.paths_file)
            print(f"Applied {changed} Apache 4(b) change notices.")
            return 0
        rendered = (
            render_markdown(args.base, args.head, rows)
            if args.format == "markdown"
            else render_tsv(args.base, args.head, rows)
        )
    except (RuntimeError, ValueError) as error:
        print(f"apache_modified_files.py: {error}", file=sys.stderr)
        return 2

    if args.output is None:
        sys.stdout.write(rendered)
    else:
        args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
